"""
build_sources.py
Reads the wyrm/ Python package and produces:
  1. wyrm-sources.js  - window.WYRM_SOURCES constant for the browser compiler
  2. Updates wyrm.html inline JSON blob (legacy, kept in sync)
  3. index.html        - clean GitHub Pages entry (links CSS + 2 JS files)

Run from the project root:
    python build_sources.py
"""

import json
import re
from pathlib import Path

SOURCE_FILES = [
    "__init__.py",
    "__main__.py",
    "ast.py",
    "lexer.py",
    "parser.py",
    "interpreter.py",
    "async_interpreter.py",
    "main.py",
    "bytecode.py",
    "llvm_codegen.py",
]

PROJECT_ROOT = Path(__file__).parent.resolve()  # wyrm root
# Adjust to actual project path if running standalone
if not (PROJECT_ROOT / "wyrm").is_dir():
    PROJECT_ROOT = Path("C:/Users/BEST/Desktop/wyrm")


def read_sources():
    wyrm_dir = PROJECT_ROOT / "wyrm"
    sources = {}
    for filename in SOURCE_FILES:
        path = wyrm_dir / filename
        if path.exists():
            print(f"  Reading {filename}...")
            sources[filename] = path.read_text(encoding="utf-8")
        else:
            print(f"  Warning: {filename} not found, skipping.")
    return sources


def write_sources_js(sources):
    """Generate wyrm-sources.js exporting window.WYRM_SOURCES"""
    out = PROJECT_ROOT / "wyrm-sources.js"
    json_str = json.dumps(sources, ensure_ascii=False, indent=None)
    content = f"// AUTO-GENERATED by build_sources.py - do not edit manually\nwindow.WYRM_SOURCES = {json_str};\n"
    out.write_text(content, encoding="utf-8")
    print(f"  Wrote {out}")


def update_html_blob(sources):
    """Keep wyrm.html inline JSON in sync (legacy)"""
    html_file = PROJECT_ROOT / "wyrm.html"
    if not html_file.exists():
        print("  wyrm.html not found, skipping blob update.")
        return
    html = html_file.read_text(encoding="utf-8")
    json_str = json.dumps(sources, ensure_ascii=False)
    pattern = r'(<script id="wyrm-sources"\s+type="application/json">).*?(</script>)'
    new_html, count = re.subn(pattern, rf'\g<1>{json_str}\g<2>', html, flags=re.DOTALL)
    if count:
        html_file.write_text(new_html, encoding="utf-8")
        print(f"  Updated wyrm.html inline JSON blob.")
    else:
        print("  Could not find wyrm-sources script tag in wyrm.html.")


def write_index_html():
    """Write index.html for GitHub Pages - links external CSS and JS files"""
    out = PROJECT_ROOT / "index.html"
    content = '''<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Wyrm - Online Compiler</title>
  <meta name="description" content="Wyrm is a modern, statically-typed systems programming language with C/C++ and Rust-comparable performance. Try it in your browser.">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Spectral:wght@600&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600;700&display=swap"
    rel="stylesheet">
  <link rel="stylesheet" href="style.css">
  <script src="https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.js"></script>
</head>

<body>

  <div class="topbar">
    <div class="brand">Wyrm<span>://</span><small>ONLINE COMPILER</small></div>
    <div class="status" id="status"><span class="dot"></span><span id="status-text">Loading Python runtime...</span>
    </div>
    <div class="topbar-right">
      <button class="theme-btn" id="theme-btn" title="Toggle Light / Dark">
        <svg class="icon-moon" viewBox="0 0 24 24" fill="currentColor">
          <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
        </svg>
        <svg class="icon-sun" viewBox="0 0 24 24" fill="currentColor">
          <path d="M12 4V2m0 20v-2m8-8h2M2 12h2m13.66-6.66 1.41-1.41M4.93 19.07l1.41-1.41m0-11.32L4.93 4.93m14.14 14.14-1.41-1.41M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0z" stroke="currentColor" stroke-width="1.7" fill="none" stroke-linecap="round" />
        </svg>
      </button>
      <button class="run-btn" id="run-btn" disabled>
        <svg viewBox="0 0 24 24" fill="currentColor">
          <path d="M8 5v14l11-7z" />
        </svg>
        Run
      </button>
    </div>
  </div>

  <div class="workspace">
    <div class="pane editor-pane">
      <div class="pane-header"><span>main.wyr</span></div>
      <div class="examples" id="examples"></div>
      <div class="editor-body">
        <div class="gutter" id="gutter">1</div>
        <div class="editor-container">
          <pre id="highlight-backdrop"></pre>
          <textarea id="code-input" spellcheck="false"
            placeholder="fn main() {&#10;    print(&quot;Hello World&quot;)&#10;}" disabled></textarea>
        </div>
      </div>
    </div>

    <div class="pane console-pane">
      <div class="pane-header">
        <span>output</span>
        <span class="action" id="clear-btn">clear</span>
      </div>
      <div id="output">
        <div class="line-sys">Waiting for Pyodide to load...</div>
      </div>
      <div class="stdin-bar" id="stdin-bar" style="display:none">
        <span class="stdin-prompt" id="stdin-prompt"></span>
        <input type="text" id="stdin-input" class="stdin-input" autocomplete="off" spellcheck="false" placeholder="type here and press Enter...">
        <button class="stdin-send" id="stdin-send">&#9166;</button>
      </div>
    </div>
  </div>

  <footer>Ctrl/Cmd+Enter to run - input() is interactive</footer>

  <!-- Wyrm Python sources (auto-generated, do not edit) -->
  <script src="wyrm-sources.js"></script>
  <script src="script.js"></script>
</body>

</html>
'''
    out.write_text(content, encoding="utf-8")
    print(f"  Wrote {out}")


def main():
    print("=== build_sources.py ===")
    print(f"Project root: {PROJECT_ROOT}")
    print()

    print("[1/3] Reading wyrm/ Python sources...")
    sources = read_sources()
    print()

    print("[2/3] Writing wyrm-sources.js...")
    write_sources_js(sources)
    print()

    print("[3/3] Updating wyrm.html inline blob & writing index.html...")
    update_html_blob(sources)
    write_index_html()
    print()

    print("Done. Files ready for GitHub Pages deployment.")


if __name__ == "__main__":
    main()
