; Module generated by Wyrm 3.1.0 Self-Hosted LLVM backend
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"
%struct.Value = type { i32, %union.anon }
%union.anon = type { double }
@wyrm_var_score = global i32 0, align 4
@.str.6 = private unnamed_addr constant [2 x i8] c"F\00", align 1
@wyrm_var_grade = global %struct.Value zeroinitializer, align 8
@.str.8 = private unnamed_addr constant [2 x i8] c"A\00", align 1
@.str.9 = private unnamed_addr constant [2 x i8] c"B\00", align 1
@.str.10 = private unnamed_addr constant [2 x i8] c"C\00", align 1
@.str.11 = private unnamed_addr constant [2 x i8] c"D\00", align 1
@.str.12 = private unnamed_addr constant [2 x i8] c"F\00", align 1
@.str.13 = private unnamed_addr constant [16 x i8] c"Your grade is: \00", align 1
@wyrm_var_count = global i32 0, align 4
@.str.15 = private unnamed_addr constant [11 x i8] c"Count is: \00", align 1
@wyrm_var_i = global i32 0, align 4
@.str.17 = private unnamed_addr constant [14 x i8] c"Breaking at 3\00", align 1
@.str.18 = private unnamed_addr constant [7 x i8] c"i is: \00", align 1
@wyrm_var_k = global i32 0, align 4
@.str.20 = private unnamed_addr constant [22 x i8] c"Skipping 2 (continue)\00", align 1
@.str.21 = private unnamed_addr constant [7 x i8] c"k is: \00", align 1
@wyrm_var_outer = global i32 0, align 4
@wyrm_var_inner = global i32 0, align 4
@.str.24 = private unnamed_addr constant [7 x i8] c"outer=\00", align 1
@.str.25 = private unnamed_addr constant [9 x i8] c", inner=\00", align 1
@wyrm_var_sum = global i32 0, align 4
@wyrm_var_n = global i32 0, align 4
@.str.28 = private unnamed_addr constant [17 x i8] c"Sum of 1 to 10: \00", align 1

declare void @llvm_val_null(ptr)
declare void @llvm_val_bool(ptr, i1)
declare void @llvm_val_number(ptr, double)
declare void @llvm_val_string(ptr, ptr)
declare void @llvm_val_array_create(ptr, i32)
declare void @llvm_val_array_init(ptr, i32, ...)
declare i1 @llvm_val_to_bool(ptr)
declare void @llvm_val_print(i32, ...)
declare void @llvm_val_input(ptr, ptr)
declare void @llvm_val_len(ptr, ptr)
declare void @llvm_val_type(ptr, ptr)
declare void @llvm_val_int(ptr, ptr)
declare void @llvm_val_float(ptr, ptr)
declare void @llvm_val_str(ptr, ptr)
declare void @llvm_val_abs(ptr, ptr)
declare void @llvm_val_round(ptr, ptr)
declare void @llvm_val_pow(ptr, ptr, ptr)
declare void @llvm_val_add(ptr, ptr, ptr)
declare void @llvm_val_sub(ptr, ptr, ptr)
declare void @llvm_val_mul(ptr, ptr, ptr)
declare void @llvm_val_div(ptr, ptr, ptr)
declare void @llvm_val_mod(ptr, ptr, ptr)
declare void @llvm_val_floordiv(ptr, ptr, ptr)
declare void @llvm_val_eq(ptr, ptr, ptr)
declare void @llvm_val_ne(ptr, ptr, ptr)
declare void @llvm_val_lt(ptr, ptr, ptr)
declare void @llvm_val_gt(ptr, ptr, ptr)
declare void @llvm_val_le(ptr, ptr, ptr)
declare void @llvm_val_ge(ptr, ptr, ptr)
declare void @llvm_val_and(ptr, ptr, ptr)
declare void @llvm_val_or(ptr, ptr, ptr)
declare void @llvm_val_not(ptr, ptr)
declare void @llvm_val_array_get(ptr, ptr, ptr)
declare void @llvm_val_array_set(ptr, ptr, ptr)
declare void @llvm_val_array_append(ptr, ptr, ptr)
declare void @llvm_val_array_pop(ptr, ptr)
declare void @llvm_val_array_slice(ptr, ptr, ptr, ptr)
declare void @llvm_val_raw_malloc(ptr, ptr)
declare void @llvm_val_raw_realloc(ptr, ptr, ptr)
declare void @llvm_val_raw_free(ptr, ptr)
declare void @llvm_val_raw_ptr(ptr, ptr)
declare void @llvm_val_arena_alloc(ptr, ptr, ptr)
declare void @llvm_val_arena_reset(ptr, ptr)
declare void @llvm_val_read_file(ptr, ptr)
declare void @llvm_val_error_val(ptr, ptr)
declare void @llvm_val_write_file(ptr, ptr, ptr)
declare void @llvm_val_exit(ptr, ptr)
declare void @llvm_val_system(ptr, ptr)
declare void @llvm_val_getenv(ptr, ptr)
declare void @llvm_val_split(ptr, ptr, ptr)
declare void @llvm_val_join(ptr, ptr, ptr)
declare void @llvm_val_trim(ptr, ptr)
declare void @llvm_val_upper(ptr, ptr)
declare void @llvm_val_lower(ptr, ptr)
declare void @llvm_val_contains(ptr, ptr, ptr)
declare void @llvm_val_replace(ptr, ptr, ptr, ptr)
declare void @llvm_val_starts_with(ptr, ptr, ptr)
declare void @llvm_val_ends_with(ptr, ptr, ptr)
declare void @llvm_val_char_at(ptr, ptr, ptr)
declare void @llvm_val_ord_val(ptr, ptr)
declare void @llvm_val_chr_val(ptr, ptr)
declare void @llvm_val_to_bytes(ptr, ptr)
declare void @llvm_val_from_bytes(ptr, ptr)
declare void @llvm_val_copy(ptr, ptr)
declare ptr @val_arena_create_wrapper(ptr)
declare void @arena_destroy(ptr)
declare void @val_init_sys_args(i32, ptr)
declare void @llvm_val_struct_create(ptr, ptr, i32)
declare void @llvm_val_struct_get(ptr, ptr, ptr)
declare void @llvm_val_struct_set(ptr, ptr, ptr)
declare void @llvm_val_from_i64(ptr, i64)
declare void @llvm_val_from_u8(ptr, i8)
declare void @llvm_val_from_f32(ptr, float)
declare void @llvm_val_from_bool(ptr, i1)
declare void @llvm_val_drop(ptr)
declare void @llvm_val_json_parse(ptr, ptr)
declare void @llvm_val_json_encode(ptr, ptr)
declare void @llvm_val_json_pretty(ptr, ptr, ptr)
declare void @llvm_val_json_get(ptr, ptr, ptr)
declare void @llvm_val_json_has(ptr, ptr, ptr)
declare void @llvm_val_json_set(ptr, ptr, ptr, ptr)
declare void @llvm_val_json_object(ptr)
declare void @llvm_val_yaml_parse(ptr, ptr)
declare void @llvm_val_yaml_encode(ptr, ptr)
declare void @llvm_val_map_new(ptr)
declare void @llvm_val_map_set(ptr, ptr, ptr, ptr)
declare void @llvm_val_map_get(ptr, ptr, ptr)
declare void @llvm_val_map_has(ptr, ptr, ptr)
declare void @llvm_val_map_del(ptr, ptr, ptr)
declare void @llvm_val_map_keys(ptr, ptr)
declare void @llvm_val_map_values(ptr, ptr)
declare void @llvm_val_map_len(ptr, ptr)
declare void @llvm_val_set_new(ptr)
declare void @llvm_val_set_add(ptr, ptr, ptr)
declare void @llvm_val_set_has(ptr, ptr, ptr)
declare void @llvm_val_set_del(ptr, ptr, ptr)
declare void @llvm_val_set_union(ptr, ptr, ptr)
declare void @llvm_val_set_intersect(ptr, ptr, ptr)
declare void @llvm_val_set_to_array(ptr, ptr)
declare void @llvm_val_sdl_init(ptr)
declare void @llvm_val_sdl_quit(ptr)
declare void @llvm_val_sdl_window(ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_destroy_window(ptr, ptr)
declare void @llvm_val_sdl_poll_event(ptr)
declare void @llvm_val_sdl_clear(ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_present(ptr, ptr)
declare void @llvm_val_sdl_draw_rect(ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_draw_line(ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_delay(ptr, ptr)
declare void @llvm_val_sdl_ticks(ptr)
declare void @llvm_val_ffi_open(ptr, ptr)
declare void @llvm_val_ffi_sym(ptr, ptr, ptr)
declare void @llvm_val_ffi_call(ptr, ptr, ptr)
declare void @llvm_val_ffi_close(ptr, ptr)
@wyrm_sys_args = external global %struct.Value, align 8


define i32 @main(i32 %argc, ptr %argv) {
  call void @val_init_sys_args(i32 %argc, ptr %argv)
  %tmp_1 = alloca %struct.Value, align 8
  %tmp_6 = alloca %struct.Value, align 8
  %tmp_10 = alloca %struct.Value, align 8
  %tmp_14 = alloca %struct.Value, align 8
  %tmp_18 = alloca %struct.Value, align 8
  %tmp_19 = alloca %struct.Value, align 8
  %tmp_20 = alloca %struct.Value, align 8
  %tmp_21 = alloca %struct.Value, align 8
  %tmp_23 = alloca %struct.Value, align 8
  %tmp_24 = alloca %struct.Value, align 8
  %tmp_25 = alloca %struct.Value, align 8
  %tmp_28 = alloca %struct.Value, align 8
  %tmp_39 = alloca %struct.Value, align 8
  %tmp_41 = alloca %struct.Value, align 8
  %tmp_42 = alloca %struct.Value, align 8
  %tmp_43 = alloca %struct.Value, align 8
  %tmp_46 = alloca %struct.Value, align 8
  %tmp_59 = alloca %struct.Value, align 8
  %tmp_61 = alloca %struct.Value, align 8
  %tmp_62 = alloca %struct.Value, align 8
  %tmp_63 = alloca %struct.Value, align 8
  %tmp_66 = alloca %struct.Value, align 8
  %tmp_72 = alloca %struct.Value, align 8
  %tmp_73 = alloca %struct.Value, align 8
  %tmp_74 = alloca %struct.Value, align 8
  %tmp_75 = alloca %struct.Value, align 8
  %tmp_76 = alloca %struct.Value, align 8
  %tmp_79 = alloca %struct.Value, align 8
  %tmp_80 = alloca %struct.Value, align 8
  %tmp_81 = alloca %struct.Value, align 8
  %tmp_84 = alloca %struct.Value, align 8
  %tmp_104 = alloca %struct.Value, align 8
  %tmp_105 = alloca %struct.Value, align 8
  %tmp_106 = alloca %struct.Value, align 8
  %tmp_109 = alloca %struct.Value, align 8
  store i32 85, ptr @wyrm_var_score, align 4
  call void @llvm_val_string(ptr %tmp_1, ptr @.str.6)
  call void @llvm_val_copy(ptr @wyrm_var_grade, ptr %tmp_1)
  %val_2 = load i32, ptr @wyrm_var_score, align 4
  %cmp_i1_3 = icmp sge i32 %val_2, 90
  br i1 %cmp_i1_3, label %then_4, label %elif_cond_4_0
then_4:
  call void @llvm_val_string(ptr %tmp_6, ptr @.str.8)
  call void @llvm_val_copy(ptr @wyrm_var_grade, ptr %tmp_6)
  br label %merge_4
elif_cond_4_0:
  %val_7 = load i32, ptr @wyrm_var_score, align 4
  %cmp_i1_8 = icmp sge i32 %val_7, 80
  br i1 %cmp_i1_8, label %elif_then_4_0, label %elif_cond_4_1
elif_then_4_0:
  call void @llvm_val_string(ptr %tmp_10, ptr @.str.9)
  call void @llvm_val_copy(ptr @wyrm_var_grade, ptr %tmp_10)
  br label %merge_4
elif_cond_4_1:
  %val_11 = load i32, ptr @wyrm_var_score, align 4
  %cmp_i1_12 = icmp sge i32 %val_11, 70
  br i1 %cmp_i1_12, label %elif_then_4_1, label %elif_cond_4_2
elif_then_4_1:
  call void @llvm_val_string(ptr %tmp_14, ptr @.str.10)
  call void @llvm_val_copy(ptr @wyrm_var_grade, ptr %tmp_14)
  br label %merge_4
elif_cond_4_2:
  %val_15 = load i32, ptr @wyrm_var_score, align 4
  %cmp_i1_16 = icmp sge i32 %val_15, 60
  br i1 %cmp_i1_16, label %elif_then_4_2, label %else_4
elif_then_4_2:
  call void @llvm_val_string(ptr %tmp_18, ptr @.str.11)
  call void @llvm_val_copy(ptr @wyrm_var_grade, ptr %tmp_18)
  br label %merge_4
else_4:
  call void @llvm_val_string(ptr %tmp_19, ptr @.str.12)
  call void @llvm_val_copy(ptr @wyrm_var_grade, ptr %tmp_19)
  br label %merge_4
merge_4:
  call void @llvm_val_string(ptr %tmp_21, ptr @.str.13)
  call void @llvm_val_add(ptr %tmp_20, ptr %tmp_21, ptr @wyrm_var_grade)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_20)
  store i32 0, ptr @wyrm_var_count, align 4
  br label %loop_21
loop_21:
  call void @llvm_val_string(ptr %tmp_24, ptr @.str.15)
  %raw_val_25 = load i32, ptr @wyrm_var_count, align 4
  %dbl_conv_26 = sitofp i32 %raw_val_25 to double
  call void @llvm_val_number(ptr %tmp_25, double %dbl_conv_26)
  call void @llvm_val_str(ptr %tmp_28, ptr %tmp_25)
  call void @llvm_val_add(ptr %tmp_23, ptr %tmp_24, ptr %tmp_28)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_23)
  %val_28 = load i32, ptr @wyrm_var_count, align 4
  %op_29 = add i32 %val_28, 1
  store i32 %op_29, ptr @wyrm_var_count, align 4
  br label %cond_21
cond_21:
  %val_31 = load i32, ptr @wyrm_var_count, align 4
  %cmp_i1_32 = icmp sge i32 %val_31, 5
  br i1 %cmp_i1_32, label %merge_21, label %loop_21
merge_21:
  store i32 0, ptr @wyrm_var_i, align 4
  br label %loop_33
loop_33:
  %val_35 = load i32, ptr @wyrm_var_i, align 4
  %cmp_i1_36 = icmp eq i32 %val_35, 3
  br i1 %cmp_i1_36, label %then_37, label %merge_37
then_37:
  call void @llvm_val_string(ptr %tmp_39, ptr @.str.17)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_39)
  br label %merge_33
dead_block_39:
  br label %merge_37
merge_37:
  call void @llvm_val_string(ptr %tmp_42, ptr @.str.18)
  %raw_val_43 = load i32, ptr @wyrm_var_i, align 4
  %dbl_conv_44 = sitofp i32 %raw_val_43 to double
  call void @llvm_val_number(ptr %tmp_43, double %dbl_conv_44)
  call void @llvm_val_str(ptr %tmp_46, ptr %tmp_43)
  call void @llvm_val_add(ptr %tmp_41, ptr %tmp_42, ptr %tmp_46)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_41)
  %val_46 = load i32, ptr @wyrm_var_i, align 4
  %op_47 = add i32 %val_46, 1
  store i32 %op_47, ptr @wyrm_var_i, align 4
  br label %cond_33
cond_33:
  %val_49 = load i32, ptr @wyrm_var_i, align 4
  %cmp_i1_50 = icmp sge i32 %val_49, 5
  br i1 %cmp_i1_50, label %merge_33, label %loop_33
merge_33:
  store i32 0, ptr @wyrm_var_k, align 4
  br label %loop_51
loop_51:
  %val_52 = load i32, ptr @wyrm_var_k, align 4
  %op_53 = add i32 %val_52, 1
  store i32 %op_53, ptr @wyrm_var_k, align 4
  %val_55 = load i32, ptr @wyrm_var_k, align 4
  %cmp_i1_56 = icmp eq i32 %val_55, 2
  br i1 %cmp_i1_56, label %then_57, label %merge_57
then_57:
  call void @llvm_val_string(ptr %tmp_59, ptr @.str.20)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_59)
  br label %cond_51
dead_block_59:
  br label %merge_57
merge_57:
  call void @llvm_val_string(ptr %tmp_62, ptr @.str.21)
  %raw_val_63 = load i32, ptr @wyrm_var_k, align 4
  %dbl_conv_64 = sitofp i32 %raw_val_63 to double
  call void @llvm_val_number(ptr %tmp_63, double %dbl_conv_64)
  call void @llvm_val_str(ptr %tmp_66, ptr %tmp_63)
  call void @llvm_val_add(ptr %tmp_61, ptr %tmp_62, ptr %tmp_66)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_61)
  br label %cond_51
cond_51:
  %val_67 = load i32, ptr @wyrm_var_k, align 4
  %cmp_i1_68 = icmp sge i32 %val_67, 4
  br i1 %cmp_i1_68, label %merge_51, label %loop_51
merge_51:
  store i32 0, ptr @wyrm_var_outer, align 4
  br label %loop_69
loop_69:
  store i32 0, ptr @wyrm_var_inner, align 4
  br label %loop_70
loop_70:
  call void @llvm_val_string(ptr %tmp_75, ptr @.str.24)
  %raw_val_76 = load i32, ptr @wyrm_var_outer, align 4
  %dbl_conv_77 = sitofp i32 %raw_val_76 to double
  call void @llvm_val_number(ptr %tmp_76, double %dbl_conv_77)
  call void @llvm_val_str(ptr %tmp_79, ptr %tmp_76)
  call void @llvm_val_add(ptr %tmp_74, ptr %tmp_75, ptr %tmp_79)
  call void @llvm_val_string(ptr %tmp_80, ptr @.str.25)
  call void @llvm_val_add(ptr %tmp_73, ptr %tmp_74, ptr %tmp_80)
  %raw_val_81 = load i32, ptr @wyrm_var_inner, align 4
  %dbl_conv_82 = sitofp i32 %raw_val_81 to double
  call void @llvm_val_number(ptr %tmp_81, double %dbl_conv_82)
  call void @llvm_val_str(ptr %tmp_84, ptr %tmp_81)
  call void @llvm_val_add(ptr %tmp_72, ptr %tmp_73, ptr %tmp_84)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_72)
  %val_84 = load i32, ptr @wyrm_var_inner, align 4
  %op_85 = add i32 %val_84, 1
  store i32 %op_85, ptr @wyrm_var_inner, align 4
  br label %cond_70
cond_70:
  %val_87 = load i32, ptr @wyrm_var_inner, align 4
  %cmp_i1_88 = icmp sge i32 %val_87, 3
  br i1 %cmp_i1_88, label %merge_70, label %loop_70
merge_70:
  %val_89 = load i32, ptr @wyrm_var_outer, align 4
  %op_90 = add i32 %val_89, 1
  store i32 %op_90, ptr @wyrm_var_outer, align 4
  br label %cond_69
cond_69:
  %val_92 = load i32, ptr @wyrm_var_outer, align 4
  %cmp_i1_93 = icmp sge i32 %val_92, 2
  br i1 %cmp_i1_93, label %merge_69, label %loop_69
merge_69:
  store i32 0, ptr @wyrm_var_sum, align 4
  store i32 1, ptr @wyrm_var_n, align 4
  br label %loop_94
loop_94:
  %val_95 = load i32, ptr @wyrm_var_sum, align 4
  %val_96 = load i32, ptr @wyrm_var_n, align 4
  %op_97 = add i32 %val_95, %val_96
  store i32 %op_97, ptr @wyrm_var_sum, align 4
  %val_98 = load i32, ptr @wyrm_var_n, align 4
  %op_99 = add i32 %val_98, 1
  store i32 %op_99, ptr @wyrm_var_n, align 4
  br label %cond_94
cond_94:
  %val_101 = load i32, ptr @wyrm_var_n, align 4
  %cmp_i1_102 = icmp sgt i32 %val_101, 10
  br i1 %cmp_i1_102, label %merge_94, label %loop_94
merge_94:
  call void @llvm_val_string(ptr %tmp_105, ptr @.str.28)
  %raw_val_106 = load i32, ptr @wyrm_var_sum, align 4
  %dbl_conv_107 = sitofp i32 %raw_val_106 to double
  call void @llvm_val_number(ptr %tmp_106, double %dbl_conv_107)
  call void @llvm_val_str(ptr %tmp_109, ptr %tmp_106)
  call void @llvm_val_add(ptr %tmp_104, ptr %tmp_105, ptr %tmp_109)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_104)
  ret i32 0
}
