; Module generated by Wyrm 3.1.0 Self-Hosted LLVM backend
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"
%struct.Value = type { i32, %union.anon }
%union.anon = type { double }
@.str.5 = private unnamed_addr constant [12 x i8] c"Hello World\00", align 1

declare void @llvm_val_null(ptr)
declare void @llvm_val_bool(ptr, i1)
declare void @llvm_val_number(ptr, double)
declare void @llvm_val_string(ptr, ptr)
declare void @llvm_val_array_create(ptr, i32)
declare void @llvm_val_array_init(ptr, i32, ...)
declare i1 @llvm_val_to_bool(ptr)
declare void @llvm_val_print(i32, ...)
declare void @llvm_val_input(ptr, ptr)
declare void @llvm_val_len(ptr, ptr)
declare void @llvm_val_type(ptr, ptr)
declare void @llvm_val_int(ptr, ptr)
declare void @llvm_val_float(ptr, ptr)
declare void @llvm_val_str(ptr, ptr)
declare void @llvm_val_abs(ptr, ptr)
declare void @llvm_val_round(ptr, ptr)
declare void @llvm_val_pow(ptr, ptr, ptr)
declare void @llvm_val_add(ptr, ptr, ptr)
declare void @llvm_val_sub(ptr, ptr, ptr)
declare void @llvm_val_mul(ptr, ptr, ptr)
declare void @llvm_val_div(ptr, ptr, ptr)
declare void @llvm_val_mod(ptr, ptr, ptr)
declare void @llvm_val_floordiv(ptr, ptr, ptr)
declare void @llvm_val_eq(ptr, ptr, ptr)
declare void @llvm_val_ne(ptr, ptr, ptr)
declare void @llvm_val_lt(ptr, ptr, ptr)
declare void @llvm_val_gt(ptr, ptr, ptr)
declare void @llvm_val_le(ptr, ptr, ptr)
declare void @llvm_val_ge(ptr, ptr, ptr)
declare void @llvm_val_and(ptr, ptr, ptr)
declare void @llvm_val_or(ptr, ptr, ptr)
declare void @llvm_val_not(ptr, ptr)
declare void @llvm_val_array_get(ptr, ptr, ptr)
declare void @llvm_val_array_set(ptr, ptr, ptr)
declare void @llvm_val_array_append(ptr, ptr, ptr)
declare void @llvm_val_array_pop(ptr, ptr)
declare void @llvm_val_array_slice(ptr, ptr, ptr, ptr)
declare void @llvm_val_raw_malloc(ptr, ptr)
declare void @llvm_val_raw_realloc(ptr, ptr, ptr)
declare void @llvm_val_raw_free(ptr, ptr)
declare void @llvm_val_raw_ptr(ptr, ptr)
declare void @llvm_val_arena_alloc(ptr, ptr, ptr)
declare void @llvm_val_arena_reset(ptr, ptr)
declare void @llvm_val_read_file(ptr, ptr)
declare void @llvm_val_error_val(ptr, ptr)
declare void @llvm_val_write_file(ptr, ptr, ptr)
declare void @llvm_val_exit(ptr, ptr)
declare void @llvm_val_system(ptr, ptr)
declare void @llvm_val_getenv(ptr, ptr)
declare void @llvm_val_split(ptr, ptr, ptr)
declare void @llvm_val_join(ptr, ptr, ptr)
declare void @llvm_val_trim(ptr, ptr)
declare void @llvm_val_upper(ptr, ptr)
declare void @llvm_val_lower(ptr, ptr)
declare void @llvm_val_contains(ptr, ptr, ptr)
declare void @llvm_val_replace(ptr, ptr, ptr, ptr)
declare void @llvm_val_starts_with(ptr, ptr, ptr)
declare void @llvm_val_ends_with(ptr, ptr, ptr)
declare void @llvm_val_char_at(ptr, ptr, ptr)
declare void @llvm_val_ord_val(ptr, ptr)
declare void @llvm_val_chr_val(ptr, ptr)
declare void @llvm_val_to_bytes(ptr, ptr)
declare void @llvm_val_from_bytes(ptr, ptr)
declare void @llvm_val_copy(ptr, ptr)
declare ptr @val_arena_create_wrapper(ptr)
declare void @arena_destroy(ptr)
declare void @val_init_sys_args(i32, ptr)
declare void @llvm_val_struct_create(ptr, ptr, i32)
declare void @llvm_val_struct_get(ptr, ptr, ptr)
declare void @llvm_val_struct_set(ptr, ptr, ptr)
declare void @llvm_val_from_i64(ptr, i64)
declare void @llvm_val_from_u8(ptr, i8)
declare void @llvm_val_from_f32(ptr, float)
declare void @llvm_val_from_bool(ptr, i1)
declare void @llvm_val_drop(ptr)
@wyrm_sys_args = external global %struct.Value, align 8

define void @wyrm_fn_main(ptr %result_ptr) {
  %tmp_1 = alloca %struct.Value, align 8
  call void @llvm_val_string(ptr %tmp_1, ptr @.str.5)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_1)
  call void @llvm_val_null(ptr %result_ptr)
  ret void
}


define i32 @main(i32 %argc, ptr %argv) {
  call void @val_init_sys_args(i32 %argc, ptr %argv)
  %tmp_main_res = alloca %struct.Value, align 8
  call void @wyrm_fn_main(ptr %tmp_main_res)
  ret i32 0
}
