; Module generated by Wyrm 3.0.0 Self-Hosted LLVM backend
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"
%struct.Value = type { i32, %union.anon }
%union.anon = type { double }
@.str.5 = private unnamed_addr constant [6 x i8] c"Point\00", align 1
@.str.6 = private unnamed_addr constant [2 x i8] c"x\00", align 1
@.str.7 = private unnamed_addr constant [2 x i8] c"y\00", align 1
@.str.8 = private unnamed_addr constant [9 x i8] c"Point x:\00", align 1
@.str.9 = private unnamed_addr constant [2 x i8] c"x\00", align 1
@.str.10 = private unnamed_addr constant [3 x i8] c"y:\00", align 1
@.str.11 = private unnamed_addr constant [2 x i8] c"y\00", align 1
@.str.12 = private unnamed_addr constant [2 x i8] c"x\00", align 1
@.str.13 = private unnamed_addr constant [2 x i8] c"y\00", align 1
@.str.14 = private unnamed_addr constant [11 x i8] c"Point sum:\00", align 1
@.str.15 = private unnamed_addr constant [23 x i8] c"Do-til finished at i =\00", align 1

declare void @llvm_val_null(ptr)
declare void @llvm_val_bool(ptr, i1)
declare void @llvm_val_number(ptr, double)
declare void @llvm_val_string(ptr, ptr)
declare void @llvm_val_array_create(ptr, i32)
declare void @llvm_val_array_init(ptr, i32, ...)
declare i1 @llvm_val_to_bool(ptr)
declare void @llvm_val_print(i32, ...)
declare void @llvm_val_input(ptr, ptr)
declare void @llvm_val_len(ptr, ptr)
declare void @llvm_val_type(ptr, ptr)
declare void @llvm_val_int(ptr, ptr)
declare void @llvm_val_float(ptr, ptr)
declare void @llvm_val_str(ptr, ptr)
declare void @llvm_val_abs(ptr, ptr)
declare void @llvm_val_round(ptr, ptr)
declare void @llvm_val_pow(ptr, ptr, ptr)
declare void @llvm_val_add(ptr, ptr, ptr)
declare void @llvm_val_sub(ptr, ptr, ptr)
declare void @llvm_val_mul(ptr, ptr, ptr)
declare void @llvm_val_div(ptr, ptr, ptr)
declare void @llvm_val_mod(ptr, ptr, ptr)
declare void @llvm_val_floordiv(ptr, ptr, ptr)
declare void @llvm_val_eq(ptr, ptr, ptr)
declare void @llvm_val_ne(ptr, ptr, ptr)
declare void @llvm_val_lt(ptr, ptr, ptr)
declare void @llvm_val_gt(ptr, ptr, ptr)
declare void @llvm_val_le(ptr, ptr, ptr)
declare void @llvm_val_ge(ptr, ptr, ptr)
declare void @llvm_val_and(ptr, ptr, ptr)
declare void @llvm_val_or(ptr, ptr, ptr)
declare void @llvm_val_not(ptr, ptr)
declare void @llvm_val_array_get(ptr, ptr, ptr)
declare void @llvm_val_array_set(ptr, ptr, ptr)
declare void @llvm_val_array_append(ptr, ptr, ptr)
declare void @llvm_val_array_pop(ptr, ptr)
declare void @llvm_val_array_slice(ptr, ptr, ptr, ptr)
declare void @llvm_val_raw_malloc(ptr, ptr)
declare void @llvm_val_raw_realloc(ptr, ptr, ptr)
declare void @llvm_val_raw_free(ptr, ptr)
declare void @llvm_val_raw_ptr(ptr, ptr)
declare void @llvm_val_arena_reset(ptr, ptr)
declare void @llvm_val_read_file(ptr, ptr)
declare void @llvm_val_error_val(ptr, ptr)
declare void @llvm_val_write_file(ptr, ptr, ptr)
declare void @llvm_val_exit(ptr, ptr)
declare void @llvm_val_system(ptr, ptr)
declare void @llvm_val_getenv(ptr, ptr)
declare void @llvm_val_split(ptr, ptr, ptr)
declare void @llvm_val_join(ptr, ptr, ptr)
declare void @llvm_val_trim(ptr, ptr)
declare void @llvm_val_upper(ptr, ptr)
declare void @llvm_val_lower(ptr, ptr)
declare void @llvm_val_contains(ptr, ptr, ptr)
declare void @llvm_val_replace(ptr, ptr, ptr, ptr)
declare void @llvm_val_starts_with(ptr, ptr, ptr)
declare void @llvm_val_ends_with(ptr, ptr, ptr)
declare void @llvm_val_char_at(ptr, ptr, ptr)
declare void @llvm_val_ord_val(ptr, ptr)
declare void @llvm_val_chr_val(ptr, ptr)
declare void @llvm_val_to_bytes(ptr, ptr)
declare void @llvm_val_from_bytes(ptr, ptr)
declare void @llvm_val_copy(ptr, ptr)
declare ptr @val_arena_create_wrapper(ptr)
declare void @arena_destroy(ptr)
declare void @val_init_sys_args(i32, ptr)
declare void @llvm_val_struct_create(ptr, ptr, i32)
declare void @llvm_val_struct_get(ptr, ptr, ptr)
declare void @llvm_val_struct_set(ptr, ptr, ptr)
@wyrm_sys_args = external global %struct.Value, align 8

define void @wyrm_fn_Point(ptr %result_ptr, ptr %arg_x, ptr %arg_y) {
  %s_ptr = alloca %struct.Value, align 8
  call void @llvm_val_struct_create(ptr %s_ptr, ptr @.str.5, i32 2)
  call void @llvm_val_struct_set(ptr %s_ptr, ptr @.str.6, ptr %arg_x)
  call void @llvm_val_struct_set(ptr %s_ptr, ptr @.str.7, ptr %arg_y)
  call void @llvm_val_copy(ptr %result_ptr, ptr %s_ptr)
  ret void
}

define void @wyrm_fn_add_points(ptr %result_ptr, ptr %arg_px, ptr %arg_py) {
  %wyrm_var_px = alloca %struct.Value, align 8
  %wyrm_var_py = alloca %struct.Value, align 8
  %tmp_1 = alloca %struct.Value, align 8
  call void @llvm_val_copy(ptr %wyrm_var_px, ptr %arg_px)
  call void @llvm_val_copy(ptr %wyrm_var_py, ptr %arg_py)
  call void @llvm_val_add(ptr %tmp_1, ptr %wyrm_var_px, ptr %wyrm_var_py)
  call void @llvm_val_copy(ptr %result_ptr, ptr %tmp_1)
  ret void
  call void @llvm_val_null(ptr %result_ptr)
  ret void
}

define void @wyrm_fn_main(ptr %result_ptr) {
  %wyrm_var_p = alloca %struct.Value, align 8
  %tmp_1 = alloca %struct.Value, align 8
  %tmp_2 = alloca %struct.Value, align 8
  %tmp_3 = alloca %struct.Value, align 8
  %tmp_4 = alloca %struct.Value, align 8
  %tmp_5 = alloca %struct.Value, align 8
  %tmp_6 = alloca %struct.Value, align 8
  %tmp_7 = alloca %struct.Value, align 8
  %wyrm_var_total = alloca i32, align 4
  %tmp_8 = alloca %struct.Value, align 8
  %tmp_9 = alloca %struct.Value, align 8
  %tmp_10 = alloca %struct.Value, align 8
  %tmp_12 = alloca %struct.Value, align 8
  %tmp_13 = alloca %struct.Value, align 8
  %wyrm_var_i = alloca i32, align 4
  %tmp_21 = alloca %struct.Value, align 8
  %tmp_22 = alloca %struct.Value, align 8
  call void @llvm_val_number(ptr %tmp_1, double 15.0)
  call void @llvm_val_number(ptr %tmp_2, double 25.0)
  call void @wyrm_fn_Point(ptr %tmp_3, ptr %tmp_1, ptr %tmp_2)
  call void @llvm_val_copy(ptr %wyrm_var_p, ptr %tmp_3)
  call void @llvm_val_string(ptr %tmp_4, ptr @.str.8)
  call void @llvm_val_struct_get(ptr %tmp_5, ptr %wyrm_var_p, ptr @.str.9)
  call void @llvm_val_string(ptr %tmp_6, ptr @.str.10)
  call void @llvm_val_struct_get(ptr %tmp_7, ptr %wyrm_var_p, ptr @.str.11)
  call void (i32, ...) @llvm_val_print(i32 4, ptr %tmp_4, ptr %tmp_5, ptr %tmp_6, ptr %tmp_7)
  call void @llvm_val_struct_get(ptr %tmp_8, ptr %wyrm_var_p, ptr @.str.12)
  call void @llvm_val_struct_get(ptr %tmp_9, ptr %wyrm_var_p, ptr @.str.13)
  call void @wyrm_fn_add_points(ptr %tmp_10, ptr %tmp_8, ptr %tmp_9)
  %union_ptr_10 = getelementptr %struct.Value, ptr %tmp_10, i32 0, i32 1
  %dbl_val_10 = load double, ptr %union_ptr_10, align 8
  %i32_val_10 = fptosi double %dbl_val_10 to i32
  store i32 %i32_val_10, ptr %wyrm_var_total, align 4
  call void @llvm_val_string(ptr %tmp_12, ptr @.str.14)
  %i32_val_13 = load i32, ptr %wyrm_var_total, align 4
  %dbl_conv_13 = sitofp i32 %i32_val_13 to double
  call void @llvm_val_number(ptr %tmp_13, double %dbl_conv_13)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_12, ptr %tmp_13)
  store i32 0, ptr %wyrm_var_i, align 4
  br label %loop_14
loop_14:
  %i32_val_15 = load i32, ptr %wyrm_var_i, align 4
  %i32_op_16 = add i32 %i32_val_15, 1
  store i32 %i32_op_16, ptr %wyrm_var_i, align 4
  br label %cond_14
cond_14:
  %i32_val_18 = load i32, ptr %wyrm_var_i, align 4
  %cmp_i1_19 = icmp sge i32 %i32_val_18, 5
  br i1 %cmp_i1_19, label %merge_14, label %loop_14
merge_14:
  call void @llvm_val_string(ptr %tmp_21, ptr @.str.15)
  %i32_val_22 = load i32, ptr %wyrm_var_i, align 4
  %dbl_conv_22 = sitofp i32 %i32_val_22 to double
  call void @llvm_val_number(ptr %tmp_22, double %dbl_conv_22)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_21, ptr %tmp_22)
  call void @llvm_val_null(ptr %result_ptr)
  ret void
}


define i32 @main(i32 %argc, ptr %argv) {
  call void @val_init_sys_args(i32 %argc, ptr %argv)
  %tmp_main_res = alloca %struct.Value, align 8
  call void @wyrm_fn_main(ptr %tmp_main_res)
  ret i32 0
}
