; Module generated by Wyrm 3.2.0 Self-Hosted LLVM backend
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"
%struct.Value = type { i32, %union.anon }
%union.anon = type { double }
@.str.5 = private unnamed_addr constant [48 x i8] c"=== Testing std.random Module in Wyrm 1.0.0 ===\00", align 1
@.str.6 = private unnamed_addr constant [42 x i8] c"[1] Testing PRNG determinism with seed...\00", align 1
@.str.7 = private unnamed_addr constant [6 x i8] c"Alpha\00", align 1
@.str.8 = private unnamed_addr constant [5 x i8] c"Beta\00", align 1
@.str.9 = private unnamed_addr constant [6 x i8] c"Gamma\00", align 1
@.str.10 = private unnamed_addr constant [6 x i8] c"Delta\00", align 1
@.str.11 = private unnamed_addr constant [6 x i8] c"Alpha\00", align 1
@.str.12 = private unnamed_addr constant [5 x i8] c"Beta\00", align 1
@.str.13 = private unnamed_addr constant [6 x i8] c"Gamma\00", align 1
@.str.14 = private unnamed_addr constant [6 x i8] c"Delta\00", align 1
@.str.15 = private unnamed_addr constant [47 x i8] c"  ✓ PRNG is strictly deterministic with seed\00", align 1
@.str.16 = private unnamed_addr constant [37 x i8] c"  ✗ PRNG determinism check failed!\00", align 1
@.str.17 = private unnamed_addr constant [44 x i8] c"[2] Testing rand_choice and rand_shuffle...\00", align 1
@.str.18 = private unnamed_addr constant [15 x i8] c"  Picked item:\00", align 1
@.str.19 = private unnamed_addr constant [12 x i8] c"  Original:\00", align 1
@.str.20 = private unnamed_addr constant [12 x i8] c"  Shuffled:\00", align 1
@.str.21 = private unnamed_addr constant [36 x i8] c"  ✓ rand_shuffle preserved length\00", align 1
@.str.22 = private unnamed_addr constant [35 x i8] c"[3] Testing CSPRNG (OS entropy)...\00", align 1
@.str.23 = private unnamed_addr constant [16 x i8] c"  Secure float:\00", align 1
@.str.24 = private unnamed_addr constant [26 x i8] c"  Secure int (1000-9999):\00", align 1
@.str.25 = private unnamed_addr constant [39 x i8] c"  Hex token (16 bytes = 32 hex chars):\00", align 1
@.str.26 = private unnamed_addr constant [27 x i8] c"  ✓ CSPRNG checks passed\00", align 1
@.str.27 = private unnamed_addr constant [32 x i8] c"  ✗ CSPRNG validation failed!\00", align 1
@.str.28 = private unnamed_addr constant [57 x i8] c"[4] Testing TRNG (Hardware RDRAND / OS Hardware pool)...\00", align 1
@.str.29 = private unnamed_addr constant [33 x i8] c"  CPU hardware RDRAND available:\00", align 1
@.str.30 = private unnamed_addr constant [14 x i8] c"  TRNG float:\00", align 1
@.str.31 = private unnamed_addr constant [20 x i8] c"  TRNG int (1-100):\00", align 1
@.str.32 = private unnamed_addr constant [28 x i8] c"  Value after TRNG re-seed:\00", align 1
@.str.33 = private unnamed_addr constant [50 x i8] c"=== All std.random tests passed successfully! ===\00", align 1

declare void @llvm_val_null(ptr)
declare void @llvm_val_bool(ptr, i1)
declare void @llvm_val_number(ptr, double)
declare void @llvm_val_string(ptr, ptr)
declare void @llvm_val_array_create(ptr, i32)
declare void @llvm_val_array_init(ptr, i32, ...)
declare i1 @llvm_val_to_bool(ptr)
declare void @llvm_val_print(i32, ...)
declare void @llvm_val_input(ptr, ptr)
declare void @llvm_val_len(ptr, ptr)
declare void @llvm_val_type(ptr, ptr)
declare void @llvm_val_int(ptr, ptr)
declare void @llvm_val_float(ptr, ptr)
declare void @llvm_val_str(ptr, ptr)
declare void @llvm_val_abs(ptr, ptr)
declare void @llvm_val_round(ptr, ptr)
declare void @llvm_val_pow(ptr, ptr, ptr)
declare void @llvm_val_add(ptr, ptr, ptr)
declare void @llvm_val_sub(ptr, ptr, ptr)
declare void @llvm_val_mul(ptr, ptr, ptr)
declare void @llvm_val_div(ptr, ptr, ptr)
declare void @llvm_val_mod(ptr, ptr, ptr)
declare void @llvm_val_floordiv(ptr, ptr, ptr)
declare void @llvm_val_eq(ptr, ptr, ptr)
declare void @llvm_val_ne(ptr, ptr, ptr)
declare void @llvm_val_lt(ptr, ptr, ptr)
declare void @llvm_val_gt(ptr, ptr, ptr)
declare void @llvm_val_le(ptr, ptr, ptr)
declare void @llvm_val_ge(ptr, ptr, ptr)
declare void @llvm_val_and(ptr, ptr, ptr)
declare void @llvm_val_or(ptr, ptr, ptr)
declare void @llvm_val_not(ptr, ptr)
declare void @llvm_val_array_get(ptr, ptr, ptr)
declare void @llvm_val_array_set(ptr, ptr, ptr)
declare void @llvm_val_array_append(ptr, ptr, ptr)
declare void @llvm_val_array_pop(ptr, ptr)
declare void @llvm_val_array_slice(ptr, ptr, ptr, ptr)
declare void @llvm_val_raw_malloc(ptr, ptr)
declare void @llvm_val_raw_realloc(ptr, ptr, ptr)
declare void @llvm_val_raw_free(ptr, ptr)
declare void @llvm_val_raw_ptr(ptr, ptr)
declare void @llvm_val_arena_alloc(ptr, ptr, ptr)
declare void @llvm_val_arena_reset(ptr, ptr)
declare void @llvm_val_read_file(ptr, ptr)
declare void @llvm_val_error_val(ptr, ptr)
declare void @llvm_val_write_file(ptr, ptr, ptr)
declare void @llvm_val_exit(ptr, ptr)
declare void @llvm_val_system(ptr, ptr)
declare void @llvm_val_getenv(ptr, ptr)
declare void @llvm_val_split(ptr, ptr, ptr)
declare void @llvm_val_join(ptr, ptr, ptr)
declare void @llvm_val_trim(ptr, ptr)
declare void @llvm_val_upper(ptr, ptr)
declare void @llvm_val_lower(ptr, ptr)
declare void @llvm_val_contains(ptr, ptr, ptr)
declare void @llvm_val_replace(ptr, ptr, ptr, ptr)
declare void @llvm_val_starts_with(ptr, ptr, ptr)
declare void @llvm_val_ends_with(ptr, ptr, ptr)
declare void @llvm_val_char_at(ptr, ptr, ptr)
declare void @llvm_val_ord_val(ptr, ptr)
declare void @llvm_val_chr_val(ptr, ptr)
declare void @llvm_val_to_bytes(ptr, ptr)
declare void @llvm_val_from_bytes(ptr, ptr)
declare void @llvm_val_copy(ptr, ptr)
declare ptr @val_arena_create_wrapper(ptr)
declare void @arena_destroy(ptr)
declare void @val_init_sys_args(i32, ptr)
declare void @llvm_val_struct_create(ptr, ptr, i32)
declare void @llvm_val_struct_get(ptr, ptr, ptr)
declare void @llvm_val_struct_set(ptr, ptr, ptr)
declare void @llvm_val_weak_ref(ptr, ptr)
declare void @llvm_val_weak_lock(ptr, ptr)
declare void @llvm_val_from_i64(ptr, i64)
declare void @llvm_val_from_u8(ptr, i8)
declare void @llvm_val_from_f32(ptr, float)
declare void @llvm_val_from_bool(ptr, i1)
declare void @llvm_val_drop(ptr)
declare void @llvm_val_json_parse(ptr, ptr)
declare void @llvm_val_json_encode(ptr, ptr)
declare void @llvm_val_json_pretty(ptr, ptr, ptr)
declare void @llvm_val_json_get(ptr, ptr, ptr)
declare void @llvm_val_json_has(ptr, ptr, ptr)
declare void @llvm_val_json_set(ptr, ptr, ptr, ptr)
declare void @llvm_val_json_object(ptr)
declare void @llvm_val_yaml_parse(ptr, ptr)
declare void @llvm_val_yaml_encode(ptr, ptr)
declare void @llvm_val_map_new(ptr)
declare void @llvm_val_map_set(ptr, ptr, ptr, ptr)
declare void @llvm_val_map_get(ptr, ptr, ptr)
declare void @llvm_val_map_has(ptr, ptr, ptr)
declare void @llvm_val_map_del(ptr, ptr, ptr)
declare void @llvm_val_map_keys(ptr, ptr)
declare void @llvm_val_map_values(ptr, ptr)
declare void @llvm_val_map_len(ptr, ptr)
declare void @llvm_val_set_new(ptr)
declare void @llvm_val_set_add(ptr, ptr, ptr)
declare void @llvm_val_set_has(ptr, ptr, ptr)
declare void @llvm_val_set_del(ptr, ptr, ptr)
declare void @llvm_val_set_union(ptr, ptr, ptr)
declare void @llvm_val_set_intersect(ptr, ptr, ptr)
declare void @llvm_val_set_to_array(ptr, ptr)
declare void @llvm_val_sdl_init(ptr)
declare void @llvm_val_sdl_quit(ptr)
declare void @llvm_val_sdl_window(ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_destroy_window(ptr, ptr)
declare void @llvm_val_sdl_poll_event(ptr)
declare void @llvm_val_sdl_clear(ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_present(ptr, ptr)
declare void @llvm_val_sdl_draw_rect(ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_draw_line(ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_delay(ptr, ptr)
declare void @llvm_val_sdl_ticks(ptr)
declare void @llvm_val_ffi_open(ptr, ptr)
declare void @llvm_val_ffi_sym(ptr, ptr, ptr)
declare void @llvm_val_ffi_call(ptr, ptr, ptr)
declare void @llvm_val_ffi_close(ptr, ptr)
declare void @llvm_val_rand_seed(ptr, ptr)
declare void @llvm_val_rand(ptr)
declare void @llvm_val_rand_int(ptr, ptr, ptr)
declare void @llvm_val_rand_range(ptr, ptr, ptr)
declare void @llvm_val_rand_choice(ptr, ptr)
declare void @llvm_val_rand_shuffle(ptr, ptr)
declare void @llvm_val_rand_secure(ptr)
declare void @llvm_val_rand_secure_int(ptr, ptr, ptr)
declare void @llvm_val_rand_bytes_hex(ptr, ptr)
declare void @llvm_val_rand_has_trng(ptr)
declare void @llvm_val_rand_trng(ptr)
declare void @llvm_val_rand_trng_int(ptr, ptr, ptr)
declare void @llvm_val_rand_reseed_trng(ptr)
declare void @llvm_val_time_now(ptr)
declare void @llvm_val_time_unix(ptr)
declare void @llvm_val_time_unix_ms(ptr)
declare void @llvm_val_time_monotonic(ptr)
declare void @llvm_val_time_monotonic_ms(ptr)
declare void @llvm_val_time_monotonic_ns(ptr)
declare void @llvm_val_time_sleep(ptr, ptr)
declare void @llvm_val_time_diff(ptr, ptr, ptr)
declare void @llvm_val_time_format(ptr, ptr, ptr)
declare void @llvm_val_time_format_local(ptr, ptr, ptr)
@wyrm_sys_args = external global %struct.Value, align 8

define void @wyrm_fn_main(ptr %result_ptr) {
  %tmp_1 = alloca %struct.Value, align 8
  %tmp_2 = alloca %struct.Value, align 8
  %tmp_3 = alloca %struct.Value, align 8
  %tmp_4 = alloca %struct.Value, align 8
  %wyrm_var_r1 = alloca %struct.Value, align 8
  %tmp_5 = alloca %struct.Value, align 8
  %wyrm_var_i1 = alloca %struct.Value, align 8
  %tmp_6 = alloca %struct.Value, align 8
  %tmp_7 = alloca %struct.Value, align 8
  %tmp_8 = alloca %struct.Value, align 8
  %wyrm_var_c1 = alloca %struct.Value, align 8
  %tmp_9 = alloca %struct.Value, align 8
  %tmp_10 = alloca %struct.Value, align 8
  %tmp_11 = alloca %struct.Value, align 8
  %tmp_12 = alloca %struct.Value, align 8
  %tmp_13 = alloca %struct.Value, align 8
  %tmp_14 = alloca %struct.Value, align 8
  %tmp_15 = alloca %struct.Value, align 8
  %tmp_16 = alloca %struct.Value, align 8
  %tmp_17 = alloca %struct.Value, align 8
  %tmp_18 = alloca %struct.Value, align 8
  %tmp_19 = alloca %struct.Value, align 8
  %tmp_20 = alloca %struct.Value, align 8
  %wyrm_var_r2 = alloca %struct.Value, align 8
  %tmp_21 = alloca %struct.Value, align 8
  %wyrm_var_i2 = alloca %struct.Value, align 8
  %tmp_22 = alloca %struct.Value, align 8
  %tmp_23 = alloca %struct.Value, align 8
  %tmp_24 = alloca %struct.Value, align 8
  %wyrm_var_c2 = alloca %struct.Value, align 8
  %tmp_25 = alloca %struct.Value, align 8
  %tmp_26 = alloca %struct.Value, align 8
  %tmp_27 = alloca %struct.Value, align 8
  %tmp_28 = alloca %struct.Value, align 8
  %tmp_29 = alloca %struct.Value, align 8
  %tmp_30 = alloca %struct.Value, align 8
  %tmp_31 = alloca %struct.Value, align 8
  %tmp_32 = alloca %struct.Value, align 8
  %tmp_33 = alloca %struct.Value, align 8
  %tmp_34 = alloca %struct.Value, align 8
  %tmp_36 = alloca %struct.Value, align 8
  %tmp_37 = alloca %struct.Value, align 8
  %tmp_38 = alloca %struct.Value, align 8
  %tmp_39 = alloca %struct.Value, align 8
  %tmp_40 = alloca %struct.Value, align 8
  %tmp_42 = alloca %struct.Value, align 8
  %tmp_43 = alloca %struct.Value, align 8
  %tmp_44 = alloca %struct.Value, align 8
  %tmp_45 = alloca %struct.Value, align 8
  %tmp_46 = alloca %struct.Value, align 8
  %wyrm_var_items = alloca %struct.Value, align 8
  %tmp_47 = alloca %struct.Value, align 8
  %tmp_48 = alloca %struct.Value, align 8
  %tmp_49 = alloca %struct.Value, align 8
  %tmp_50 = alloca %struct.Value, align 8
  %tmp_51 = alloca %struct.Value, align 8
  %tmp_52 = alloca %struct.Value, align 8
  %tmp_53 = alloca %struct.Value, align 8
  %tmp_54 = alloca %struct.Value, align 8
  %tmp_55 = alloca %struct.Value, align 8
  %tmp_56 = alloca %struct.Value, align 8
  %tmp_57 = alloca %struct.Value, align 8
  %tmp_58 = alloca %struct.Value, align 8
  %tmp_59 = alloca %struct.Value, align 8
  %wyrm_var_picked = alloca %struct.Value, align 8
  %tmp_60 = alloca %struct.Value, align 8
  %tmp_61 = alloca %struct.Value, align 8
  %wyrm_var_shuffled = alloca %struct.Value, align 8
  %tmp_62 = alloca %struct.Value, align 8
  %tmp_63 = alloca %struct.Value, align 8
  %tmp_64 = alloca %struct.Value, align 8
  %tmp_66 = alloca %struct.Value, align 8
  %tmp_67 = alloca %struct.Value, align 8
  %tmp_68 = alloca %struct.Value, align 8
  %tmp_70 = alloca %struct.Value, align 8
  %tmp_71 = alloca %struct.Value, align 8
  %wyrm_var_sec_float = alloca %struct.Value, align 8
  %tmp_72 = alloca %struct.Value, align 8
  %wyrm_var_sec_int = alloca %struct.Value, align 8
  %tmp_73 = alloca %struct.Value, align 8
  %tmp_74 = alloca %struct.Value, align 8
  %tmp_75 = alloca %struct.Value, align 8
  %wyrm_var_hex_token = alloca %struct.Value, align 8
  %tmp_76 = alloca %struct.Value, align 8
  %tmp_77 = alloca %struct.Value, align 8
  %tmp_78 = alloca %struct.Value, align 8
  %tmp_79 = alloca %struct.Value, align 8
  %tmp_80 = alloca %struct.Value, align 8
  %tmp_82 = alloca %struct.Value, align 8
  %tmp_83 = alloca %struct.Value, align 8
  %tmp_84 = alloca %struct.Value, align 8
  %tmp_85 = alloca %struct.Value, align 8
  %tmp_86 = alloca %struct.Value, align 8
  %tmp_87 = alloca %struct.Value, align 8
  %tmp_88 = alloca %struct.Value, align 8
  %tmp_89 = alloca %struct.Value, align 8
  %tmp_90 = alloca %struct.Value, align 8
  %tmp_91 = alloca %struct.Value, align 8
  %tmp_92 = alloca %struct.Value, align 8
  %tmp_93 = alloca %struct.Value, align 8
  %tmp_94 = alloca %struct.Value, align 8
  %tmp_95 = alloca %struct.Value, align 8
  %tmp_96 = alloca %struct.Value, align 8
  %tmp_98 = alloca %struct.Value, align 8
  %tmp_99 = alloca %struct.Value, align 8
  %tmp_100 = alloca %struct.Value, align 8
  %tmp_101 = alloca %struct.Value, align 8
  %tmp_102 = alloca %struct.Value, align 8
  %wyrm_var_has_hw = alloca %struct.Value, align 8
  %tmp_103 = alloca %struct.Value, align 8
  %tmp_104 = alloca %struct.Value, align 8
  %wyrm_var_trng_float = alloca %struct.Value, align 8
  %tmp_105 = alloca %struct.Value, align 8
  %wyrm_var_trng_val = alloca %struct.Value, align 8
  %tmp_106 = alloca %struct.Value, align 8
  %tmp_107 = alloca %struct.Value, align 8
  %tmp_108 = alloca %struct.Value, align 8
  %tmp_109 = alloca %struct.Value, align 8
  %tmp_110 = alloca %struct.Value, align 8
  %tmp_111 = alloca %struct.Value, align 8
  %wyrm_var_after_reseed = alloca %struct.Value, align 8
  %tmp_112 = alloca %struct.Value, align 8
  %tmp_113 = alloca %struct.Value, align 8
  %tmp_114 = alloca %struct.Value, align 8
  call void @llvm_val_string(ptr %tmp_1, ptr @.str.5)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_1)
  call void @llvm_val_string(ptr %tmp_2, ptr @.str.6)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_2)
  call void @llvm_val_number(ptr %tmp_3, double 98765.0)
  call void @llvm_val_rand_seed(ptr %tmp_4, ptr %tmp_3)
  call void @llvm_val_rand(ptr %tmp_5)
  call void @llvm_val_copy(ptr %wyrm_var_r1, ptr %tmp_5)
  call void @llvm_val_drop(ptr %tmp_5)
  call void @llvm_val_number(ptr %tmp_6, double 1.0)
  call void @llvm_val_number(ptr %tmp_7, double 1000.0)
  call void @llvm_val_rand_int(ptr %tmp_8, ptr %tmp_6, ptr %tmp_7)
  call void @llvm_val_copy(ptr %wyrm_var_i1, ptr %tmp_8)
  call void @llvm_val_drop(ptr %tmp_8)
  call void @llvm_val_array_create(ptr %tmp_9, i32 4)
  call void @llvm_val_string(ptr %tmp_10, ptr @.str.7)
  call void @llvm_val_number(ptr %tmp_11, double 0.0)
  call void @llvm_val_array_set(ptr %tmp_9, ptr %tmp_11, ptr %tmp_10)
  call void @llvm_val_string(ptr %tmp_12, ptr @.str.8)
  call void @llvm_val_number(ptr %tmp_13, double 1.0)
  call void @llvm_val_array_set(ptr %tmp_9, ptr %tmp_13, ptr %tmp_12)
  call void @llvm_val_string(ptr %tmp_14, ptr @.str.9)
  call void @llvm_val_number(ptr %tmp_15, double 2.0)
  call void @llvm_val_array_set(ptr %tmp_9, ptr %tmp_15, ptr %tmp_14)
  call void @llvm_val_string(ptr %tmp_16, ptr @.str.10)
  call void @llvm_val_number(ptr %tmp_17, double 3.0)
  call void @llvm_val_array_set(ptr %tmp_9, ptr %tmp_17, ptr %tmp_16)
  call void @llvm_val_rand_choice(ptr %tmp_18, ptr %tmp_9)
  call void @llvm_val_copy(ptr %wyrm_var_c1, ptr %tmp_18)
  call void @llvm_val_drop(ptr %tmp_18)
  call void @llvm_val_number(ptr %tmp_19, double 98765.0)
  call void @llvm_val_rand_seed(ptr %tmp_20, ptr %tmp_19)
  call void @llvm_val_rand(ptr %tmp_21)
  call void @llvm_val_copy(ptr %wyrm_var_r2, ptr %tmp_21)
  call void @llvm_val_drop(ptr %tmp_21)
  call void @llvm_val_number(ptr %tmp_22, double 1.0)
  call void @llvm_val_number(ptr %tmp_23, double 1000.0)
  call void @llvm_val_rand_int(ptr %tmp_24, ptr %tmp_22, ptr %tmp_23)
  call void @llvm_val_copy(ptr %wyrm_var_i2, ptr %tmp_24)
  call void @llvm_val_drop(ptr %tmp_24)
  call void @llvm_val_array_create(ptr %tmp_25, i32 4)
  call void @llvm_val_string(ptr %tmp_26, ptr @.str.11)
  call void @llvm_val_number(ptr %tmp_27, double 0.0)
  call void @llvm_val_array_set(ptr %tmp_25, ptr %tmp_27, ptr %tmp_26)
  call void @llvm_val_string(ptr %tmp_28, ptr @.str.12)
  call void @llvm_val_number(ptr %tmp_29, double 1.0)
  call void @llvm_val_array_set(ptr %tmp_25, ptr %tmp_29, ptr %tmp_28)
  call void @llvm_val_string(ptr %tmp_30, ptr @.str.13)
  call void @llvm_val_number(ptr %tmp_31, double 2.0)
  call void @llvm_val_array_set(ptr %tmp_25, ptr %tmp_31, ptr %tmp_30)
  call void @llvm_val_string(ptr %tmp_32, ptr @.str.14)
  call void @llvm_val_number(ptr %tmp_33, double 3.0)
  call void @llvm_val_array_set(ptr %tmp_25, ptr %tmp_33, ptr %tmp_32)
  call void @llvm_val_rand_choice(ptr %tmp_34, ptr %tmp_25)
  call void @llvm_val_copy(ptr %wyrm_var_c2, ptr %tmp_34)
  call void @llvm_val_drop(ptr %tmp_34)
  call void @llvm_val_eq(ptr %tmp_38, ptr %wyrm_var_r1, ptr %wyrm_var_r2)
  call void @llvm_val_eq(ptr %tmp_39, ptr %wyrm_var_i1, ptr %wyrm_var_i2)
  call void @llvm_val_and(ptr %tmp_37, ptr %tmp_38, ptr %tmp_39)
  call void @llvm_val_eq(ptr %tmp_40, ptr %wyrm_var_c1, ptr %wyrm_var_c2)
  call void @llvm_val_and(ptr %tmp_36, ptr %tmp_37, ptr %tmp_40)
  %cond_i1_34 = call i1 @llvm_val_to_bool(ptr %tmp_36)
  br i1 %cond_i1_34, label %then_40, label %else_40
then_40:
  call void @llvm_val_string(ptr %tmp_42, ptr @.str.15)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_42)
  br label %merge_40
else_40:
  call void @llvm_val_string(ptr %tmp_43, ptr @.str.16)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_43)
  call void @llvm_val_number(ptr %tmp_44, double 1.0)
  call void @llvm_val_exit(ptr %tmp_45, ptr %tmp_44)
  br label %merge_40
merge_40:
  call void @llvm_val_string(ptr %tmp_46, ptr @.str.17)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_46)
  call void @llvm_val_array_create(ptr %tmp_47, i32 6)
  call void @llvm_val_number(ptr %tmp_48, double 10.0)
  call void @llvm_val_number(ptr %tmp_49, double 0.0)
  call void @llvm_val_array_set(ptr %tmp_47, ptr %tmp_49, ptr %tmp_48)
  call void @llvm_val_number(ptr %tmp_50, double 20.0)
  call void @llvm_val_number(ptr %tmp_51, double 1.0)
  call void @llvm_val_array_set(ptr %tmp_47, ptr %tmp_51, ptr %tmp_50)
  call void @llvm_val_number(ptr %tmp_52, double 30.0)
  call void @llvm_val_number(ptr %tmp_53, double 2.0)
  call void @llvm_val_array_set(ptr %tmp_47, ptr %tmp_53, ptr %tmp_52)
  call void @llvm_val_number(ptr %tmp_54, double 40.0)
  call void @llvm_val_number(ptr %tmp_55, double 3.0)
  call void @llvm_val_array_set(ptr %tmp_47, ptr %tmp_55, ptr %tmp_54)
  call void @llvm_val_number(ptr %tmp_56, double 50.0)
  call void @llvm_val_number(ptr %tmp_57, double 4.0)
  call void @llvm_val_array_set(ptr %tmp_47, ptr %tmp_57, ptr %tmp_56)
  call void @llvm_val_number(ptr %tmp_58, double 60.0)
  call void @llvm_val_number(ptr %tmp_59, double 5.0)
  call void @llvm_val_array_set(ptr %tmp_47, ptr %tmp_59, ptr %tmp_58)
  call void @llvm_val_copy(ptr %wyrm_var_items, ptr %tmp_47)
  call void @llvm_val_rand_choice(ptr %tmp_60, ptr %wyrm_var_items)
  call void @llvm_val_copy(ptr %wyrm_var_picked, ptr %tmp_60)
  call void @llvm_val_drop(ptr %tmp_60)
  call void @llvm_val_string(ptr %tmp_61, ptr @.str.18)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_61, ptr %wyrm_var_picked)
  call void @llvm_val_rand_shuffle(ptr %tmp_62, ptr %wyrm_var_items)
  call void @llvm_val_copy(ptr %wyrm_var_shuffled, ptr %tmp_62)
  call void @llvm_val_drop(ptr %tmp_62)
  call void @llvm_val_string(ptr %tmp_63, ptr @.str.19)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_63, ptr %wyrm_var_items)
  call void @llvm_val_string(ptr %tmp_64, ptr @.str.20)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_64, ptr %wyrm_var_shuffled)
  call void @llvm_val_len(ptr %tmp_67, ptr %wyrm_var_shuffled)
  call void @llvm_val_len(ptr %tmp_68, ptr %wyrm_var_items)
  call void @llvm_val_eq(ptr %tmp_66, ptr %tmp_67, ptr %tmp_68)
  %cond_i1_64 = call i1 @llvm_val_to_bool(ptr %tmp_66)
  br i1 %cond_i1_64, label %then_68, label %merge_68
then_68:
  call void @llvm_val_string(ptr %tmp_70, ptr @.str.21)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_70)
  br label %merge_68
merge_68:
  call void @llvm_val_string(ptr %tmp_71, ptr @.str.22)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_71)
  call void @llvm_val_rand_secure(ptr %tmp_72)
  call void @llvm_val_copy(ptr %wyrm_var_sec_float, ptr %tmp_72)
  call void @llvm_val_drop(ptr %tmp_72)
  call void @llvm_val_number(ptr %tmp_73, double 1000.0)
  call void @llvm_val_number(ptr %tmp_74, double 9999.0)
  call void @llvm_val_rand_secure_int(ptr %tmp_75, ptr %tmp_73, ptr %tmp_74)
  call void @llvm_val_copy(ptr %wyrm_var_sec_int, ptr %tmp_75)
  call void @llvm_val_drop(ptr %tmp_75)
  call void @llvm_val_number(ptr %tmp_76, double 16.0)
  call void @llvm_val_rand_bytes_hex(ptr %tmp_77, ptr %tmp_76)
  call void @llvm_val_copy(ptr %wyrm_var_hex_token, ptr %tmp_77)
  call void @llvm_val_drop(ptr %tmp_77)
  call void @llvm_val_string(ptr %tmp_78, ptr @.str.23)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_78, ptr %wyrm_var_sec_float)
  call void @llvm_val_string(ptr %tmp_79, ptr @.str.24)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_79, ptr %wyrm_var_sec_int)
  call void @llvm_val_string(ptr %tmp_80, ptr @.str.25)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_80, ptr %wyrm_var_hex_token)
  call void @llvm_val_number(ptr %tmp_87, double 0.0)
  call void @llvm_val_ge(ptr %tmp_86, ptr %wyrm_var_sec_float, ptr %tmp_87)
  call void @llvm_val_number(ptr %tmp_89, double 1.0)
  call void @llvm_val_lt(ptr %tmp_88, ptr %wyrm_var_sec_float, ptr %tmp_89)
  call void @llvm_val_and(ptr %tmp_85, ptr %tmp_86, ptr %tmp_88)
  call void @llvm_val_number(ptr %tmp_91, double 1000.0)
  call void @llvm_val_ge(ptr %tmp_90, ptr %wyrm_var_sec_int, ptr %tmp_91)
  call void @llvm_val_and(ptr %tmp_84, ptr %tmp_85, ptr %tmp_90)
  call void @llvm_val_number(ptr %tmp_93, double 9999.0)
  call void @llvm_val_le(ptr %tmp_92, ptr %wyrm_var_sec_int, ptr %tmp_93)
  call void @llvm_val_and(ptr %tmp_83, ptr %tmp_84, ptr %tmp_92)
  call void @llvm_val_len(ptr %tmp_95, ptr %wyrm_var_hex_token)
  call void @llvm_val_number(ptr %tmp_96, double 32.0)
  call void @llvm_val_eq(ptr %tmp_94, ptr %tmp_95, ptr %tmp_96)
  call void @llvm_val_and(ptr %tmp_82, ptr %tmp_83, ptr %tmp_94)
  %cond_i1_80 = call i1 @llvm_val_to_bool(ptr %tmp_82)
  br i1 %cond_i1_80, label %then_96, label %else_96
then_96:
  call void @llvm_val_string(ptr %tmp_98, ptr @.str.26)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_98)
  br label %merge_96
else_96:
  call void @llvm_val_string(ptr %tmp_99, ptr @.str.27)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_99)
  call void @llvm_val_number(ptr %tmp_100, double 1.0)
  call void @llvm_val_exit(ptr %tmp_101, ptr %tmp_100)
  br label %merge_96
merge_96:
  call void @llvm_val_string(ptr %tmp_102, ptr @.str.28)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_102)
  call void @llvm_val_rand_has_trng(ptr %tmp_103)
  call void @llvm_val_copy(ptr %wyrm_var_has_hw, ptr %tmp_103)
  call void @llvm_val_drop(ptr %tmp_103)
  call void @llvm_val_string(ptr %tmp_104, ptr @.str.29)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_104, ptr %wyrm_var_has_hw)
  call void @llvm_val_rand_trng(ptr %tmp_105)
  call void @llvm_val_copy(ptr %wyrm_var_trng_float, ptr %tmp_105)
  call void @llvm_val_drop(ptr %tmp_105)
  call void @llvm_val_number(ptr %tmp_106, double 1.0)
  call void @llvm_val_number(ptr %tmp_107, double 100.0)
  call void @llvm_val_rand_trng_int(ptr %tmp_108, ptr %tmp_106, ptr %tmp_107)
  call void @llvm_val_copy(ptr %wyrm_var_trng_val, ptr %tmp_108)
  call void @llvm_val_drop(ptr %tmp_108)
  call void @llvm_val_string(ptr %tmp_109, ptr @.str.30)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_109, ptr %wyrm_var_trng_float)
  call void @llvm_val_string(ptr %tmp_110, ptr @.str.31)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_110, ptr %wyrm_var_trng_val)
  call void @llvm_val_rand_reseed_trng(ptr %tmp_111)
  call void @llvm_val_rand(ptr %tmp_112)
  call void @llvm_val_copy(ptr %wyrm_var_after_reseed, ptr %tmp_112)
  call void @llvm_val_drop(ptr %tmp_112)
  call void @llvm_val_string(ptr %tmp_113, ptr @.str.32)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_113, ptr %wyrm_var_after_reseed)
  call void @llvm_val_string(ptr %tmp_114, ptr @.str.33)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_114)
  call void @llvm_val_null(ptr %result_ptr)
  ret void
}


define i32 @main(i32 %argc, ptr %argv) {
  call void @val_init_sys_args(i32 %argc, ptr %argv)
  %tmp_main_res = alloca %struct.Value, align 8
  call void @wyrm_fn_main(ptr %tmp_main_res)
  ret i32 0
}
