; Module generated by Wyrm 3.1.0 Self-Hosted LLVM backend
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"
%struct.Value = type { i32, %union.anon }
%union.anon = type { double }
@.str.5 = private unnamed_addr constant [9 x i8] c"Resource\00", align 1
@.str.6 = private unnamed_addr constant [3 x i8] c"id\00", align 1
@.str.7 = private unnamed_addr constant [4 x i8] c"tag\00", align 1
@.str.8 = private unnamed_addr constant [37 x i8] c"Inside create_resource: created id =\00", align 1
@.str.9 = private unnamed_addr constant [3 x i8] c"id\00", align 1
@.str.10 = private unnamed_addr constant [6 x i8] c"tag =\00", align 1
@.str.11 = private unnamed_addr constant [4 x i8] c"tag\00", align 1
@.str.12 = private unnamed_addr constant [55 x i8] c"=== Wyrm v3.1.0 Ownership and Arena Allocator Test ===\00", align 1
@.str.13 = private unnamed_addr constant [31 x i8] c"[1] Testing Arena Allocator...\00", align 1
@.str.14 = private unnamed_addr constant [39 x i8] c"Allocated chunk1 (256 bytes) from pool\00", align 1
@.str.15 = private unnamed_addr constant [39 x i8] c"Allocated chunk2 (512 bytes) from pool\00", align 1
@.str.16 = private unnamed_addr constant [30 x i8] c"Arena pool reset successfully\00", align 1
@.str.17 = private unnamed_addr constant [32 x i8] c"[2] Testing Scoped Ownership...\00", align 1
@.str.18 = private unnamed_addr constant [8 x i8] c"primary\00", align 1
@.str.19 = private unnamed_addr constant [30 x i8] c"Caller received resource id =\00", align 1
@.str.20 = private unnamed_addr constant [3 x i8] c"id\00", align 1
@.str.21 = private unnamed_addr constant [6 x i8] c"tag =\00", align 1
@.str.22 = private unnamed_addr constant [4 x i8] c"tag\00", align 1
@.str.23 = private unnamed_addr constant [5 x i8] c"temp\00", align 1
@.str.24 = private unnamed_addr constant [15 x i8] c"Loop iteration\00", align 1
@.str.25 = private unnamed_addr constant [19 x i8] c"owns temp_res id =\00", align 1
@.str.26 = private unnamed_addr constant [3 x i8] c"id\00", align 1
@.str.27 = private unnamed_addr constant [48 x i8] c"Loop finished, scoped resources dropped cleanly\00", align 1
@.str.28 = private unnamed_addr constant [58 x i8] c"=== All Ownership and Arena Tests Passed Successfully ===\00", align 1

declare void @llvm_val_null(ptr)
declare void @llvm_val_bool(ptr, i1)
declare void @llvm_val_number(ptr, double)
declare void @llvm_val_string(ptr, ptr)
declare void @llvm_val_array_create(ptr, i32)
declare void @llvm_val_array_init(ptr, i32, ...)
declare i1 @llvm_val_to_bool(ptr)
declare void @llvm_val_print(i32, ...)
declare void @llvm_val_input(ptr, ptr)
declare void @llvm_val_len(ptr, ptr)
declare void @llvm_val_type(ptr, ptr)
declare void @llvm_val_int(ptr, ptr)
declare void @llvm_val_float(ptr, ptr)
declare void @llvm_val_str(ptr, ptr)
declare void @llvm_val_abs(ptr, ptr)
declare void @llvm_val_round(ptr, ptr)
declare void @llvm_val_pow(ptr, ptr, ptr)
declare void @llvm_val_add(ptr, ptr, ptr)
declare void @llvm_val_sub(ptr, ptr, ptr)
declare void @llvm_val_mul(ptr, ptr, ptr)
declare void @llvm_val_div(ptr, ptr, ptr)
declare void @llvm_val_mod(ptr, ptr, ptr)
declare void @llvm_val_floordiv(ptr, ptr, ptr)
declare void @llvm_val_eq(ptr, ptr, ptr)
declare void @llvm_val_ne(ptr, ptr, ptr)
declare void @llvm_val_lt(ptr, ptr, ptr)
declare void @llvm_val_gt(ptr, ptr, ptr)
declare void @llvm_val_le(ptr, ptr, ptr)
declare void @llvm_val_ge(ptr, ptr, ptr)
declare void @llvm_val_and(ptr, ptr, ptr)
declare void @llvm_val_or(ptr, ptr, ptr)
declare void @llvm_val_not(ptr, ptr)
declare void @llvm_val_array_get(ptr, ptr, ptr)
declare void @llvm_val_array_set(ptr, ptr, ptr)
declare void @llvm_val_array_append(ptr, ptr, ptr)
declare void @llvm_val_array_pop(ptr, ptr)
declare void @llvm_val_array_slice(ptr, ptr, ptr, ptr)
declare void @llvm_val_raw_malloc(ptr, ptr)
declare void @llvm_val_raw_realloc(ptr, ptr, ptr)
declare void @llvm_val_raw_free(ptr, ptr)
declare void @llvm_val_raw_ptr(ptr, ptr)
declare void @llvm_val_arena_alloc(ptr, ptr, ptr)
declare void @llvm_val_arena_reset(ptr, ptr)
declare void @llvm_val_read_file(ptr, ptr)
declare void @llvm_val_error_val(ptr, ptr)
declare void @llvm_val_write_file(ptr, ptr, ptr)
declare void @llvm_val_exit(ptr, ptr)
declare void @llvm_val_system(ptr, ptr)
declare void @llvm_val_getenv(ptr, ptr)
declare void @llvm_val_split(ptr, ptr, ptr)
declare void @llvm_val_join(ptr, ptr, ptr)
declare void @llvm_val_trim(ptr, ptr)
declare void @llvm_val_upper(ptr, ptr)
declare void @llvm_val_lower(ptr, ptr)
declare void @llvm_val_contains(ptr, ptr, ptr)
declare void @llvm_val_replace(ptr, ptr, ptr, ptr)
declare void @llvm_val_starts_with(ptr, ptr, ptr)
declare void @llvm_val_ends_with(ptr, ptr, ptr)
declare void @llvm_val_char_at(ptr, ptr, ptr)
declare void @llvm_val_ord_val(ptr, ptr)
declare void @llvm_val_chr_val(ptr, ptr)
declare void @llvm_val_to_bytes(ptr, ptr)
declare void @llvm_val_from_bytes(ptr, ptr)
declare void @llvm_val_copy(ptr, ptr)
declare ptr @val_arena_create_wrapper(ptr)
declare void @arena_destroy(ptr)
declare void @val_init_sys_args(i32, ptr)
declare void @llvm_val_struct_create(ptr, ptr, i32)
declare void @llvm_val_struct_get(ptr, ptr, ptr)
declare void @llvm_val_struct_set(ptr, ptr, ptr)
declare void @llvm_val_from_i64(ptr, i64)
declare void @llvm_val_from_u8(ptr, i8)
declare void @llvm_val_from_f32(ptr, float)
declare void @llvm_val_from_bool(ptr, i1)
declare void @llvm_val_drop(ptr)
declare void @llvm_val_json_parse(ptr, ptr)
declare void @llvm_val_json_encode(ptr, ptr)
declare void @llvm_val_json_pretty(ptr, ptr, ptr)
declare void @llvm_val_json_get(ptr, ptr, ptr)
declare void @llvm_val_json_has(ptr, ptr, ptr)
declare void @llvm_val_json_set(ptr, ptr, ptr, ptr)
declare void @llvm_val_json_object(ptr)
declare void @llvm_val_yaml_parse(ptr, ptr)
declare void @llvm_val_yaml_encode(ptr, ptr)
declare void @llvm_val_map_new(ptr)
declare void @llvm_val_map_set(ptr, ptr, ptr, ptr)
declare void @llvm_val_map_get(ptr, ptr, ptr)
declare void @llvm_val_map_has(ptr, ptr, ptr)
declare void @llvm_val_map_del(ptr, ptr, ptr)
declare void @llvm_val_map_keys(ptr, ptr)
declare void @llvm_val_map_values(ptr, ptr)
declare void @llvm_val_map_len(ptr, ptr)
declare void @llvm_val_set_new(ptr)
declare void @llvm_val_set_add(ptr, ptr, ptr)
declare void @llvm_val_set_has(ptr, ptr, ptr)
declare void @llvm_val_set_del(ptr, ptr, ptr)
declare void @llvm_val_set_union(ptr, ptr, ptr)
declare void @llvm_val_set_intersect(ptr, ptr, ptr)
declare void @llvm_val_set_to_array(ptr, ptr)
declare void @llvm_val_sdl_init(ptr)
declare void @llvm_val_sdl_quit(ptr)
declare void @llvm_val_sdl_window(ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_destroy_window(ptr, ptr)
declare void @llvm_val_sdl_poll_event(ptr)
declare void @llvm_val_sdl_clear(ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_present(ptr, ptr)
declare void @llvm_val_sdl_draw_rect(ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_draw_line(ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_delay(ptr, ptr)
declare void @llvm_val_sdl_ticks(ptr)
declare void @llvm_val_ffi_open(ptr, ptr)
declare void @llvm_val_ffi_sym(ptr, ptr, ptr)
declare void @llvm_val_ffi_call(ptr, ptr, ptr)
declare void @llvm_val_ffi_close(ptr, ptr)
@wyrm_sys_args = external global %struct.Value, align 8

define void @wyrm_fn_Resource(ptr %result_ptr, ptr %arg_id, ptr %arg_tag) {
  %s_ptr = alloca %struct.Value, align 8
  call void @llvm_val_struct_create(ptr %s_ptr, ptr @.str.5, i32 2)
  call void @llvm_val_struct_set(ptr %s_ptr, ptr @.str.6, ptr %arg_id)
  call void @llvm_val_struct_set(ptr %s_ptr, ptr @.str.7, ptr %arg_tag)
  call void @llvm_val_copy(ptr %result_ptr, ptr %s_ptr)
  ret void
}

define void @wyrm_fn_create_resource(ptr %result_ptr, ptr %arg_id, ptr %arg_tag) {
  %wyrm_var_id = alloca %struct.Value, align 8
  %wyrm_var_tag = alloca %struct.Value, align 8
  %wyrm_var_r = alloca %struct.Value, align 8
  %tmp_1 = alloca %struct.Value, align 8
  %tmp_2 = alloca %struct.Value, align 8
  %tmp_3 = alloca %struct.Value, align 8
  %tmp_4 = alloca %struct.Value, align 8
  %tmp_5 = alloca %struct.Value, align 8
  call void @llvm_val_copy(ptr %wyrm_var_id, ptr %arg_id)
  call void @llvm_val_copy(ptr %wyrm_var_tag, ptr %arg_tag)
  call void @wyrm_fn_Resource(ptr %tmp_1, ptr %wyrm_var_id, ptr %wyrm_var_tag)
  call void @llvm_val_copy(ptr %wyrm_var_r, ptr %tmp_1)
  call void @llvm_val_string(ptr %tmp_2, ptr @.str.8)
  call void @llvm_val_struct_get(ptr %tmp_3, ptr %wyrm_var_r, ptr @.str.9)
  call void @llvm_val_string(ptr %tmp_4, ptr @.str.10)
  call void @llvm_val_struct_get(ptr %tmp_5, ptr %wyrm_var_r, ptr @.str.11)
  call void (i32, ...) @llvm_val_print(i32 4, ptr %tmp_2, ptr %tmp_3, ptr %tmp_4, ptr %tmp_5)
  call void @llvm_val_copy(ptr %result_ptr, ptr %wyrm_var_r)
  ret void
  call void @llvm_val_null(ptr %result_ptr)
  ret void
}

define void @wyrm_fn_main(ptr %result_ptr) {
  %tmp_1 = alloca %struct.Value, align 8
  %tmp_2 = alloca %struct.Value, align 8
  %tmp_3 = alloca %struct.Value, align 8
  %wyrm_var_chunk1 = alloca %struct.Value, align 8
  %tmp_4 = alloca %struct.Value, align 8
  %tmp_5 = alloca %struct.Value, align 8
  %tmp_6 = alloca %struct.Value, align 8
  %wyrm_var_chunk2 = alloca %struct.Value, align 8
  %tmp_7 = alloca %struct.Value, align 8
  %tmp_8 = alloca %struct.Value, align 8
  %tmp_9 = alloca %struct.Value, align 8
  %tmp_10 = alloca %struct.Value, align 8
  %tmp_11 = alloca %struct.Value, align 8
  %tmp_12 = alloca %struct.Value, align 8
  %wyrm_var_res = alloca %struct.Value, align 8
  %tmp_13 = alloca %struct.Value, align 8
  %tmp_14 = alloca %struct.Value, align 8
  %tmp_15 = alloca %struct.Value, align 8
  %tmp_16 = alloca %struct.Value, align 8
  %tmp_17 = alloca %struct.Value, align 8
  %tmp_18 = alloca %struct.Value, align 8
  %tmp_19 = alloca %struct.Value, align 8
  %wyrm_var_count = alloca i32, align 4
  %wyrm_var_temp_res = alloca %struct.Value, align 8
  %tmp_21 = alloca %struct.Value, align 8
  %tmp_24 = alloca %struct.Value, align 8
  %tmp_25 = alloca %struct.Value, align 8
  %tmp_26 = alloca %struct.Value, align 8
  %tmp_27 = alloca %struct.Value, align 8
  %tmp_30 = alloca %struct.Value, align 8
  %tmp_31 = alloca %struct.Value, align 8
  %tmp_37 = alloca %struct.Value, align 8
  %tmp_38 = alloca %struct.Value, align 8
  call void @llvm_val_string(ptr %tmp_1, ptr @.str.12)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_1)
  call void @llvm_val_string(ptr %tmp_2, ptr @.str.13)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_2)
  call void @llvm_val_number(ptr %tmp_3, double 4096.0)
  %wyrm_arena_pool = call ptr @val_arena_create_wrapper(ptr %tmp_3)
  call void @llvm_val_number(ptr %tmp_5, double 256.0)
  call void @llvm_val_arena_alloc(ptr %tmp_4, ptr %wyrm_arena_pool, ptr %tmp_5)
  call void @llvm_val_copy(ptr %wyrm_var_chunk1, ptr %tmp_4)
  call void @llvm_val_string(ptr %tmp_6, ptr @.str.14)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_6)
  call void @llvm_val_number(ptr %tmp_8, double 512.0)
  call void @llvm_val_arena_alloc(ptr %tmp_7, ptr %wyrm_arena_pool, ptr %tmp_8)
  call void @llvm_val_copy(ptr %wyrm_var_chunk2, ptr %tmp_7)
  call void @llvm_val_string(ptr %tmp_9, ptr @.str.15)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_9)
  call void @llvm_val_arena_reset(ptr %tmp_10, ptr %wyrm_arena_pool)
  call void @llvm_val_string(ptr %tmp_11, ptr @.str.16)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_11)
  call void @llvm_val_string(ptr %tmp_12, ptr @.str.17)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_12)
  call void @llvm_val_number(ptr %tmp_13, double 101.0)
  call void @llvm_val_string(ptr %tmp_14, ptr @.str.18)
  call void @wyrm_fn_create_resource(ptr %tmp_15, ptr %tmp_13, ptr %tmp_14)
  call void @llvm_val_copy(ptr %wyrm_var_res, ptr %tmp_15)
  call void @llvm_val_string(ptr %tmp_16, ptr @.str.19)
  call void @llvm_val_struct_get(ptr %tmp_17, ptr %wyrm_var_res, ptr @.str.20)
  call void @llvm_val_string(ptr %tmp_18, ptr @.str.21)
  call void @llvm_val_struct_get(ptr %tmp_19, ptr %wyrm_var_res, ptr @.str.22)
  call void (i32, ...) @llvm_val_print(i32 4, ptr %tmp_16, ptr %tmp_17, ptr %tmp_18, ptr %tmp_19)
  store i32 0, ptr %wyrm_var_count, align 4
  br label %loop_19
loop_19:
  %raw_val_21 = load i32, ptr %wyrm_var_count, align 4
  %dbl_conv_22 = sitofp i32 %raw_val_21 to double
  call void @llvm_val_number(ptr %tmp_21, double %dbl_conv_22)
  call void @llvm_val_string(ptr %tmp_24, ptr @.str.23)
  call void @wyrm_fn_Resource(ptr %tmp_25, ptr %tmp_21, ptr %tmp_24)
  call void @llvm_val_copy(ptr %wyrm_var_temp_res, ptr %tmp_25)
  call void @llvm_val_string(ptr %tmp_26, ptr @.str.24)
  %raw_val_27 = load i32, ptr %wyrm_var_count, align 4
  %dbl_conv_28 = sitofp i32 %raw_val_27 to double
  call void @llvm_val_number(ptr %tmp_27, double %dbl_conv_28)
  call void @llvm_val_string(ptr %tmp_30, ptr @.str.25)
  call void @llvm_val_struct_get(ptr %tmp_31, ptr %wyrm_var_temp_res, ptr @.str.26)
  call void (i32, ...) @llvm_val_print(i32 4, ptr %tmp_26, ptr %tmp_27, ptr %tmp_30, ptr %tmp_31)
  %val_31 = load i32, ptr %wyrm_var_count, align 4
  %op_32 = add i32 %val_31, 1
  store i32 %op_32, ptr %wyrm_var_count, align 4
  br label %cond_19
cond_19:
  %val_34 = load i32, ptr %wyrm_var_count, align 4
  %cmp_i1_35 = icmp sge i32 %val_34, 3
  br i1 %cmp_i1_35, label %merge_19, label %loop_19
merge_19:
  call void @llvm_val_string(ptr %tmp_37, ptr @.str.27)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_37)
  call void @llvm_val_string(ptr %tmp_38, ptr @.str.28)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_38)
  call void @llvm_val_null(ptr %result_ptr)
  ret void
}


define i32 @main(i32 %argc, ptr %argv) {
  call void @val_init_sys_args(i32 %argc, ptr %argv)
  %tmp_main_res = alloca %struct.Value, align 8
  call void @wyrm_fn_main(ptr %tmp_main_res)
  ret i32 0
}
