; Module generated by Wyrm 3.2.0 Self-Hosted LLVM backend
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"
%struct.Value = type { i32, %union.anon }
%union.anon = type { double }
@.str.5 = private unnamed_addr constant [19 x i8] c"ASSERTION FAILED: \00", align 1
@.str.6 = private unnamed_addr constant [46 x i8] c"=== Testing std.time Module in Wyrm 1.0.0 ===\00", align 1
@.str.7 = private unnamed_addr constant [17 x i8] c"[1] time_now(): \00", align 1
@.str.8 = private unnamed_addr constant [40 x i8] c"time_now() should be greater than 1.7e9\00", align 1
@.str.9 = private unnamed_addr constant [18 x i8] c"[2] time_unix(): \00", align 1
@.str.10 = private unnamed_addr constant [58 x i8] c"time_unix() should be greater than or equal to 1700000000\00", align 1
@.str.11 = private unnamed_addr constant [21 x i8] c"[3] time_unix_ms(): \00", align 1
@.str.12 = private unnamed_addr constant [45 x i8] c"time_unix_ms() should be greater than 1.7e12\00", align 1
@.str.13 = private unnamed_addr constant [23 x i8] c"[4] Monotonic timers: \00", align 1
@.str.14 = private unnamed_addr constant [6 x i8] c" s | \00", align 1
@.str.15 = private unnamed_addr constant [7 x i8] c" ms | \00", align 1
@.str.16 = private unnamed_addr constant [4 x i8] c" ns\00", align 1
@.str.17 = private unnamed_addr constant [30 x i8] c"m_sec1 should be non-negative\00", align 1
@.str.18 = private unnamed_addr constant [29 x i8] c"m_ms1 should be non-negative\00", align 1
@.str.19 = private unnamed_addr constant [29 x i8] c"m_ns1 should be non-negative\00", align 1
@.str.20 = private unnamed_addr constant [33 x i8] c"[5] Testing time_sleep(50 ms)...\00", align 1
@.str.21 = private unnamed_addr constant [25 x i8] c"    Elapsed sleep time: \00", align 1
@.str.22 = private unnamed_addr constant [4 x i8] c" ms\00", align 1
@.str.23 = private unnamed_addr constant [62 x i8] c"Sleep of 50ms should measure at least 35ms on monotonic clock\00", align 1
@.str.24 = private unnamed_addr constant [16 x i8] c"[6] time_diff: \00", align 1
@.str.25 = private unnamed_addr constant [4 x i8] c" ms\00", align 1
@.str.26 = private unnamed_addr constant [35 x i8] c"time_diff should equal end - start\00", align 1
@.str.27 = private unnamed_addr constant [9 x i8] c"%Y-%m-%d\00", align 1
@.str.28 = private unnamed_addr constant [36 x i8] c"[7] Formatted UTC Date (%Y-%m-%d): \00", align 1
@.str.29 = private unnamed_addr constant [48 x i8] c"Formatted date '%Y-%m-%d' should have length 10\00", align 1
@.str.30 = private unnamed_addr constant [2 x i8] c"-\00", align 1
@.str.31 = private unnamed_addr constant [24 x i8] c"Expected '-' at index 4\00", align 1
@.str.32 = private unnamed_addr constant [2 x i8] c"-\00", align 1
@.str.33 = private unnamed_addr constant [24 x i8] c"Expected '-' at index 7\00", align 1
@.str.34 = private unnamed_addr constant [18 x i8] c"%Y-%m-%d %H:%M:%S\00", align 1
@.str.35 = private unnamed_addr constant [32 x i8] c"[8] Formatted Local Date/Time: \00", align 1
@.str.36 = private unnamed_addr constant [47 x i8] c"Formatted local datetime should have length 19\00", align 1
@.str.37 = private unnamed_addr constant [32 x i8] c"[9] Default Format (null fmt): \00", align 1
@.str.38 = private unnamed_addr constant [47 x i8] c"Default formatted string should have length 19\00", align 1
@.str.39 = private unnamed_addr constant [48 x i8] c"=== All std.time tests passed successfully! ===\00", align 1

declare void @llvm_val_null(ptr)
declare void @llvm_val_bool(ptr, i1)
declare void @llvm_val_number(ptr, double)
declare void @llvm_val_string(ptr, ptr)
declare void @llvm_val_array_create(ptr, i32)
declare void @llvm_val_array_init(ptr, i32, ...)
declare i1 @llvm_val_to_bool(ptr)
declare void @llvm_val_print(i32, ...)
declare void @llvm_val_input(ptr, ptr)
declare void @llvm_val_len(ptr, ptr)
declare void @llvm_val_type(ptr, ptr)
declare void @llvm_val_int(ptr, ptr)
declare void @llvm_val_float(ptr, ptr)
declare void @llvm_val_str(ptr, ptr)
declare void @llvm_val_abs(ptr, ptr)
declare void @llvm_val_round(ptr, ptr)
declare void @llvm_val_pow(ptr, ptr, ptr)
declare void @llvm_val_add(ptr, ptr, ptr)
declare void @llvm_val_sub(ptr, ptr, ptr)
declare void @llvm_val_mul(ptr, ptr, ptr)
declare void @llvm_val_div(ptr, ptr, ptr)
declare void @llvm_val_mod(ptr, ptr, ptr)
declare void @llvm_val_floordiv(ptr, ptr, ptr)
declare void @llvm_val_eq(ptr, ptr, ptr)
declare void @llvm_val_ne(ptr, ptr, ptr)
declare void @llvm_val_lt(ptr, ptr, ptr)
declare void @llvm_val_gt(ptr, ptr, ptr)
declare void @llvm_val_le(ptr, ptr, ptr)
declare void @llvm_val_ge(ptr, ptr, ptr)
declare void @llvm_val_and(ptr, ptr, ptr)
declare void @llvm_val_or(ptr, ptr, ptr)
declare void @llvm_val_not(ptr, ptr)
declare void @llvm_val_array_get(ptr, ptr, ptr)
declare void @llvm_val_array_set(ptr, ptr, ptr)
declare void @llvm_val_array_append(ptr, ptr, ptr)
declare void @llvm_val_array_pop(ptr, ptr)
declare void @llvm_val_array_slice(ptr, ptr, ptr, ptr)
declare void @llvm_val_raw_malloc(ptr, ptr)
declare void @llvm_val_raw_realloc(ptr, ptr, ptr)
declare void @llvm_val_raw_free(ptr, ptr)
declare void @llvm_val_raw_ptr(ptr, ptr)
declare void @llvm_val_arena_alloc(ptr, ptr, ptr)
declare void @llvm_val_arena_reset(ptr, ptr)
declare void @llvm_val_read_file(ptr, ptr)
declare void @llvm_val_error_val(ptr, ptr)
declare void @llvm_val_write_file(ptr, ptr, ptr)
declare void @llvm_val_exit(ptr, ptr)
declare void @llvm_val_system(ptr, ptr)
declare void @llvm_val_getenv(ptr, ptr)
declare void @llvm_val_split(ptr, ptr, ptr)
declare void @llvm_val_join(ptr, ptr, ptr)
declare void @llvm_val_trim(ptr, ptr)
declare void @llvm_val_upper(ptr, ptr)
declare void @llvm_val_lower(ptr, ptr)
declare void @llvm_val_contains(ptr, ptr, ptr)
declare void @llvm_val_replace(ptr, ptr, ptr, ptr)
declare void @llvm_val_starts_with(ptr, ptr, ptr)
declare void @llvm_val_ends_with(ptr, ptr, ptr)
declare void @llvm_val_char_at(ptr, ptr, ptr)
declare void @llvm_val_ord_val(ptr, ptr)
declare void @llvm_val_chr_val(ptr, ptr)
declare void @llvm_val_to_bytes(ptr, ptr)
declare void @llvm_val_from_bytes(ptr, ptr)
declare void @llvm_val_copy(ptr, ptr)
declare ptr @val_arena_create_wrapper(ptr)
declare void @arena_destroy(ptr)
declare void @val_init_sys_args(i32, ptr)
declare void @llvm_val_struct_create(ptr, ptr, i32)
declare void @llvm_val_struct_get(ptr, ptr, ptr)
declare void @llvm_val_struct_set(ptr, ptr, ptr)
declare void @llvm_val_weak_ref(ptr, ptr)
declare void @llvm_val_weak_lock(ptr, ptr)
declare void @llvm_val_from_i64(ptr, i64)
declare void @llvm_val_from_u8(ptr, i8)
declare void @llvm_val_from_f32(ptr, float)
declare void @llvm_val_from_bool(ptr, i1)
declare void @llvm_val_drop(ptr)
declare void @llvm_val_json_parse(ptr, ptr)
declare void @llvm_val_json_encode(ptr, ptr)
declare void @llvm_val_json_pretty(ptr, ptr, ptr)
declare void @llvm_val_json_get(ptr, ptr, ptr)
declare void @llvm_val_json_has(ptr, ptr, ptr)
declare void @llvm_val_json_set(ptr, ptr, ptr, ptr)
declare void @llvm_val_json_object(ptr)
declare void @llvm_val_yaml_parse(ptr, ptr)
declare void @llvm_val_yaml_encode(ptr, ptr)
declare void @llvm_val_map_new(ptr)
declare void @llvm_val_map_set(ptr, ptr, ptr, ptr)
declare void @llvm_val_map_get(ptr, ptr, ptr)
declare void @llvm_val_map_has(ptr, ptr, ptr)
declare void @llvm_val_map_del(ptr, ptr, ptr)
declare void @llvm_val_map_keys(ptr, ptr)
declare void @llvm_val_map_values(ptr, ptr)
declare void @llvm_val_map_len(ptr, ptr)
declare void @llvm_val_set_new(ptr)
declare void @llvm_val_set_add(ptr, ptr, ptr)
declare void @llvm_val_set_has(ptr, ptr, ptr)
declare void @llvm_val_set_del(ptr, ptr, ptr)
declare void @llvm_val_set_union(ptr, ptr, ptr)
declare void @llvm_val_set_intersect(ptr, ptr, ptr)
declare void @llvm_val_set_to_array(ptr, ptr)
declare void @llvm_val_sdl_init(ptr)
declare void @llvm_val_sdl_quit(ptr)
declare void @llvm_val_sdl_window(ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_destroy_window(ptr, ptr)
declare void @llvm_val_sdl_poll_event(ptr)
declare void @llvm_val_sdl_clear(ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_present(ptr, ptr)
declare void @llvm_val_sdl_draw_rect(ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_draw_line(ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_delay(ptr, ptr)
declare void @llvm_val_sdl_ticks(ptr)
declare void @llvm_val_ffi_open(ptr, ptr)
declare void @llvm_val_ffi_sym(ptr, ptr, ptr)
declare void @llvm_val_ffi_call(ptr, ptr, ptr)
declare void @llvm_val_ffi_close(ptr, ptr)
declare void @llvm_val_rand_seed(ptr, ptr)
declare void @llvm_val_rand(ptr)
declare void @llvm_val_rand_int(ptr, ptr, ptr)
declare void @llvm_val_rand_range(ptr, ptr, ptr)
declare void @llvm_val_rand_choice(ptr, ptr)
declare void @llvm_val_rand_shuffle(ptr, ptr)
declare void @llvm_val_rand_secure(ptr)
declare void @llvm_val_rand_secure_int(ptr, ptr, ptr)
declare void @llvm_val_rand_bytes_hex(ptr, ptr)
declare void @llvm_val_rand_has_trng(ptr)
declare void @llvm_val_rand_trng(ptr)
declare void @llvm_val_rand_trng_int(ptr, ptr, ptr)
declare void @llvm_val_rand_reseed_trng(ptr)
declare void @llvm_val_time_now(ptr)
declare void @llvm_val_time_unix(ptr)
declare void @llvm_val_time_unix_ms(ptr)
declare void @llvm_val_time_monotonic(ptr)
declare void @llvm_val_time_monotonic_ms(ptr)
declare void @llvm_val_time_monotonic_ns(ptr)
declare void @llvm_val_time_sleep(ptr, ptr)
declare void @llvm_val_time_diff(ptr, ptr, ptr)
declare void @llvm_val_time_format(ptr, ptr, ptr)
declare void @llvm_val_time_format_local(ptr, ptr, ptr)
@wyrm_sys_args = external global %struct.Value, align 8

define void @wyrm_fn_assert(ptr %result_ptr, ptr %arg_condition, ptr %arg_message) {
  %wyrm_var_condition = alloca %struct.Value, align 8
  %wyrm_var_message = alloca %struct.Value, align 8
  %tmp_2 = alloca %struct.Value, align 8
  %tmp_4 = alloca %struct.Value, align 8
  %tmp_5 = alloca %struct.Value, align 8
  %tmp_6 = alloca %struct.Value, align 8
  %tmp_7 = alloca %struct.Value, align 8
  call void @llvm_val_copy(ptr %wyrm_var_condition, ptr %arg_condition)
  call void @llvm_val_copy(ptr %wyrm_var_message, ptr %arg_message)
  call void @llvm_val_not(ptr %tmp_2, ptr %wyrm_var_condition)
  %cond_i1_0 = call i1 @llvm_val_to_bool(ptr %tmp_2)
  br i1 %cond_i1_0, label %then_2, label %merge_2
then_2:
  call void @llvm_val_string(ptr %tmp_5, ptr @.str.5)
  call void @llvm_val_add(ptr %tmp_4, ptr %tmp_5, ptr %wyrm_var_message)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_4)
  call void @llvm_val_number(ptr %tmp_6, double 1.0)
  call void @llvm_val_exit(ptr %tmp_7, ptr %tmp_6)
  br label %merge_2
merge_2:
  call void @llvm_val_null(ptr %result_ptr)
  ret void
}

define void @wyrm_fn_main(ptr %result_ptr) {
  %tmp_1 = alloca %struct.Value, align 8
  %wyrm_var_now_sec = alloca %struct.Value, align 8
  %tmp_2 = alloca %struct.Value, align 8
  %tmp_3 = alloca %struct.Value, align 8
  %tmp_4 = alloca %struct.Value, align 8
  %tmp_5 = alloca %struct.Value, align 8
  %tmp_6 = alloca %struct.Value, align 8
  %tmp_7 = alloca %struct.Value, align 8
  %tmp_8 = alloca %struct.Value, align 8
  %tmp_9 = alloca %struct.Value, align 8
  %wyrm_var_unix_sec = alloca %struct.Value, align 8
  %tmp_10 = alloca %struct.Value, align 8
  %tmp_11 = alloca %struct.Value, align 8
  %tmp_12 = alloca %struct.Value, align 8
  %tmp_13 = alloca %struct.Value, align 8
  %tmp_14 = alloca %struct.Value, align 8
  %tmp_15 = alloca %struct.Value, align 8
  %tmp_16 = alloca %struct.Value, align 8
  %tmp_17 = alloca %struct.Value, align 8
  %wyrm_var_unix_ms = alloca %struct.Value, align 8
  %tmp_18 = alloca %struct.Value, align 8
  %tmp_19 = alloca %struct.Value, align 8
  %tmp_20 = alloca %struct.Value, align 8
  %tmp_21 = alloca %struct.Value, align 8
  %tmp_22 = alloca %struct.Value, align 8
  %tmp_23 = alloca %struct.Value, align 8
  %tmp_24 = alloca %struct.Value, align 8
  %tmp_25 = alloca %struct.Value, align 8
  %wyrm_var_m_sec1 = alloca %struct.Value, align 8
  %tmp_26 = alloca %struct.Value, align 8
  %wyrm_var_m_ms1 = alloca %struct.Value, align 8
  %tmp_27 = alloca %struct.Value, align 8
  %wyrm_var_m_ns1 = alloca %struct.Value, align 8
  %tmp_28 = alloca %struct.Value, align 8
  %tmp_29 = alloca %struct.Value, align 8
  %tmp_30 = alloca %struct.Value, align 8
  %tmp_31 = alloca %struct.Value, align 8
  %tmp_32 = alloca %struct.Value, align 8
  %tmp_33 = alloca %struct.Value, align 8
  %tmp_34 = alloca %struct.Value, align 8
  %tmp_35 = alloca %struct.Value, align 8
  %tmp_36 = alloca %struct.Value, align 8
  %tmp_37 = alloca %struct.Value, align 8
  %tmp_38 = alloca %struct.Value, align 8
  %tmp_39 = alloca %struct.Value, align 8
  %tmp_40 = alloca %struct.Value, align 8
  %tmp_41 = alloca %struct.Value, align 8
  %tmp_42 = alloca %struct.Value, align 8
  %tmp_43 = alloca %struct.Value, align 8
  %tmp_44 = alloca %struct.Value, align 8
  %tmp_45 = alloca %struct.Value, align 8
  %tmp_46 = alloca %struct.Value, align 8
  %tmp_47 = alloca %struct.Value, align 8
  %tmp_48 = alloca %struct.Value, align 8
  %tmp_49 = alloca %struct.Value, align 8
  %tmp_50 = alloca %struct.Value, align 8
  %tmp_51 = alloca %struct.Value, align 8
  %tmp_52 = alloca %struct.Value, align 8
  %tmp_53 = alloca %struct.Value, align 8
  %tmp_54 = alloca %struct.Value, align 8
  %wyrm_var_start_ms = alloca %struct.Value, align 8
  %tmp_55 = alloca %struct.Value, align 8
  %tmp_56 = alloca %struct.Value, align 8
  %tmp_57 = alloca %struct.Value, align 8
  %wyrm_var_end_ms = alloca %struct.Value, align 8
  %tmp_58 = alloca %struct.Value, align 8
  %wyrm_var_delta_ms = alloca %struct.Value, align 8
  %tmp_59 = alloca %struct.Value, align 8
  %tmp_60 = alloca %struct.Value, align 8
  %tmp_61 = alloca %struct.Value, align 8
  %tmp_62 = alloca %struct.Value, align 8
  %tmp_63 = alloca %struct.Value, align 8
  %tmp_64 = alloca %struct.Value, align 8
  %tmp_65 = alloca %struct.Value, align 8
  %tmp_66 = alloca %struct.Value, align 8
  %tmp_67 = alloca %struct.Value, align 8
  %tmp_68 = alloca %struct.Value, align 8
  %wyrm_var_diff_result = alloca %struct.Value, align 8
  %tmp_69 = alloca %struct.Value, align 8
  %tmp_70 = alloca %struct.Value, align 8
  %tmp_71 = alloca %struct.Value, align 8
  %tmp_72 = alloca %struct.Value, align 8
  %tmp_73 = alloca %struct.Value, align 8
  %tmp_74 = alloca %struct.Value, align 8
  %tmp_75 = alloca %struct.Value, align 8
  %tmp_76 = alloca %struct.Value, align 8
  %tmp_77 = alloca %struct.Value, align 8
  %wyrm_var_date_str = alloca %struct.Value, align 8
  %tmp_78 = alloca %struct.Value, align 8
  %tmp_79 = alloca %struct.Value, align 8
  %tmp_80 = alloca %struct.Value, align 8
  %tmp_81 = alloca %struct.Value, align 8
  %tmp_82 = alloca %struct.Value, align 8
  %tmp_83 = alloca %struct.Value, align 8
  %tmp_84 = alloca %struct.Value, align 8
  %tmp_85 = alloca %struct.Value, align 8
  %tmp_86 = alloca %struct.Value, align 8
  %tmp_87 = alloca %struct.Value, align 8
  %tmp_88 = alloca %struct.Value, align 8
  %tmp_89 = alloca %struct.Value, align 8
  %tmp_90 = alloca %struct.Value, align 8
  %tmp_91 = alloca %struct.Value, align 8
  %tmp_92 = alloca %struct.Value, align 8
  %tmp_93 = alloca %struct.Value, align 8
  %tmp_94 = alloca %struct.Value, align 8
  %tmp_95 = alloca %struct.Value, align 8
  %tmp_96 = alloca %struct.Value, align 8
  %tmp_97 = alloca %struct.Value, align 8
  %tmp_98 = alloca %struct.Value, align 8
  %wyrm_var_local_date_str = alloca %struct.Value, align 8
  %tmp_99 = alloca %struct.Value, align 8
  %tmp_100 = alloca %struct.Value, align 8
  %tmp_101 = alloca %struct.Value, align 8
  %tmp_102 = alloca %struct.Value, align 8
  %tmp_103 = alloca %struct.Value, align 8
  %tmp_104 = alloca %struct.Value, align 8
  %tmp_105 = alloca %struct.Value, align 8
  %tmp_106 = alloca %struct.Value, align 8
  %tmp_107 = alloca %struct.Value, align 8
  %wyrm_var_default_fmt_str = alloca %struct.Value, align 8
  %tmp_108 = alloca %struct.Value, align 8
  %tmp_109 = alloca %struct.Value, align 8
  %tmp_110 = alloca %struct.Value, align 8
  %tmp_111 = alloca %struct.Value, align 8
  %tmp_112 = alloca %struct.Value, align 8
  %tmp_113 = alloca %struct.Value, align 8
  %tmp_114 = alloca %struct.Value, align 8
  %tmp_115 = alloca %struct.Value, align 8
  %tmp_116 = alloca %struct.Value, align 8
  %tmp_117 = alloca %struct.Value, align 8
  call void @llvm_val_string(ptr %tmp_1, ptr @.str.6)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_1)
  call void @llvm_val_time_now(ptr %tmp_2)
  call void @llvm_val_copy(ptr %wyrm_var_now_sec, ptr %tmp_2)
  call void @llvm_val_drop(ptr %tmp_2)
  call void @llvm_val_string(ptr %tmp_4, ptr @.str.7)
  call void @llvm_val_str(ptr %tmp_5, ptr %wyrm_var_now_sec)
  call void @llvm_val_add(ptr %tmp_3, ptr %tmp_4, ptr %tmp_5)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_3)
  call void @llvm_val_number(ptr %tmp_7, double 1700000000.0)
  call void @llvm_val_gt(ptr %tmp_6, ptr %wyrm_var_now_sec, ptr %tmp_7)
  call void @llvm_val_string(ptr %tmp_8, ptr @.str.8)
  call void @wyrm_fn_assert(ptr %tmp_9, ptr %tmp_6, ptr %tmp_8)
  call void @llvm_val_time_unix(ptr %tmp_10)
  call void @llvm_val_copy(ptr %wyrm_var_unix_sec, ptr %tmp_10)
  call void @llvm_val_drop(ptr %tmp_10)
  call void @llvm_val_string(ptr %tmp_12, ptr @.str.9)
  call void @llvm_val_str(ptr %tmp_13, ptr %wyrm_var_unix_sec)
  call void @llvm_val_add(ptr %tmp_11, ptr %tmp_12, ptr %tmp_13)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_11)
  call void @llvm_val_number(ptr %tmp_15, double 1700000000.0)
  call void @llvm_val_ge(ptr %tmp_14, ptr %wyrm_var_unix_sec, ptr %tmp_15)
  call void @llvm_val_string(ptr %tmp_16, ptr @.str.10)
  call void @wyrm_fn_assert(ptr %tmp_17, ptr %tmp_14, ptr %tmp_16)
  call void @llvm_val_time_unix_ms(ptr %tmp_18)
  call void @llvm_val_copy(ptr %wyrm_var_unix_ms, ptr %tmp_18)
  call void @llvm_val_drop(ptr %tmp_18)
  call void @llvm_val_string(ptr %tmp_20, ptr @.str.11)
  call void @llvm_val_str(ptr %tmp_21, ptr %wyrm_var_unix_ms)
  call void @llvm_val_add(ptr %tmp_19, ptr %tmp_20, ptr %tmp_21)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_19)
  call void @llvm_val_number(ptr %tmp_23, double 1700000000000.0)
  call void @llvm_val_gt(ptr %tmp_22, ptr %wyrm_var_unix_ms, ptr %tmp_23)
  call void @llvm_val_string(ptr %tmp_24, ptr @.str.12)
  call void @wyrm_fn_assert(ptr %tmp_25, ptr %tmp_22, ptr %tmp_24)
  call void @llvm_val_time_monotonic(ptr %tmp_26)
  call void @llvm_val_copy(ptr %wyrm_var_m_sec1, ptr %tmp_26)
  call void @llvm_val_drop(ptr %tmp_26)
  call void @llvm_val_time_monotonic_ms(ptr %tmp_27)
  call void @llvm_val_copy(ptr %wyrm_var_m_ms1, ptr %tmp_27)
  call void @llvm_val_drop(ptr %tmp_27)
  call void @llvm_val_time_monotonic_ns(ptr %tmp_28)
  call void @llvm_val_copy(ptr %wyrm_var_m_ns1, ptr %tmp_28)
  call void @llvm_val_drop(ptr %tmp_28)
  call void @llvm_val_string(ptr %tmp_35, ptr @.str.13)
  call void @llvm_val_str(ptr %tmp_36, ptr %wyrm_var_m_sec1)
  call void @llvm_val_add(ptr %tmp_34, ptr %tmp_35, ptr %tmp_36)
  call void @llvm_val_string(ptr %tmp_37, ptr @.str.14)
  call void @llvm_val_add(ptr %tmp_33, ptr %tmp_34, ptr %tmp_37)
  call void @llvm_val_str(ptr %tmp_38, ptr %wyrm_var_m_ms1)
  call void @llvm_val_add(ptr %tmp_32, ptr %tmp_33, ptr %tmp_38)
  call void @llvm_val_string(ptr %tmp_39, ptr @.str.15)
  call void @llvm_val_add(ptr %tmp_31, ptr %tmp_32, ptr %tmp_39)
  call void @llvm_val_str(ptr %tmp_40, ptr %wyrm_var_m_ns1)
  call void @llvm_val_add(ptr %tmp_30, ptr %tmp_31, ptr %tmp_40)
  call void @llvm_val_string(ptr %tmp_41, ptr @.str.16)
  call void @llvm_val_add(ptr %tmp_29, ptr %tmp_30, ptr %tmp_41)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_29)
  call void @llvm_val_number(ptr %tmp_43, double 0.0)
  call void @llvm_val_ge(ptr %tmp_42, ptr %wyrm_var_m_sec1, ptr %tmp_43)
  call void @llvm_val_string(ptr %tmp_44, ptr @.str.17)
  call void @wyrm_fn_assert(ptr %tmp_45, ptr %tmp_42, ptr %tmp_44)
  call void @llvm_val_number(ptr %tmp_47, double 0.0)
  call void @llvm_val_ge(ptr %tmp_46, ptr %wyrm_var_m_ms1, ptr %tmp_47)
  call void @llvm_val_string(ptr %tmp_48, ptr @.str.18)
  call void @wyrm_fn_assert(ptr %tmp_49, ptr %tmp_46, ptr %tmp_48)
  call void @llvm_val_number(ptr %tmp_51, double 0.0)
  call void @llvm_val_ge(ptr %tmp_50, ptr %wyrm_var_m_ns1, ptr %tmp_51)
  call void @llvm_val_string(ptr %tmp_52, ptr @.str.19)
  call void @wyrm_fn_assert(ptr %tmp_53, ptr %tmp_50, ptr %tmp_52)
  call void @llvm_val_string(ptr %tmp_54, ptr @.str.20)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_54)
  call void @llvm_val_time_monotonic_ms(ptr %tmp_55)
  call void @llvm_val_copy(ptr %wyrm_var_start_ms, ptr %tmp_55)
  call void @llvm_val_drop(ptr %tmp_55)
  call void @llvm_val_number(ptr %tmp_56, double 50.0)
  call void @llvm_val_time_sleep(ptr %tmp_57, ptr %tmp_56)
  call void @llvm_val_time_monotonic_ms(ptr %tmp_58)
  call void @llvm_val_copy(ptr %wyrm_var_end_ms, ptr %tmp_58)
  call void @llvm_val_drop(ptr %tmp_58)
  call void @llvm_val_sub(ptr %tmp_59, ptr %wyrm_var_end_ms, ptr %wyrm_var_start_ms)
  call void @llvm_val_copy(ptr %wyrm_var_delta_ms, ptr %tmp_59)
  call void @llvm_val_string(ptr %tmp_62, ptr @.str.21)
  call void @llvm_val_str(ptr %tmp_63, ptr %wyrm_var_delta_ms)
  call void @llvm_val_add(ptr %tmp_61, ptr %tmp_62, ptr %tmp_63)
  call void @llvm_val_string(ptr %tmp_64, ptr @.str.22)
  call void @llvm_val_add(ptr %tmp_60, ptr %tmp_61, ptr %tmp_64)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_60)
  call void @llvm_val_number(ptr %tmp_66, double 35.0)
  call void @llvm_val_ge(ptr %tmp_65, ptr %wyrm_var_delta_ms, ptr %tmp_66)
  call void @llvm_val_string(ptr %tmp_67, ptr @.str.23)
  call void @wyrm_fn_assert(ptr %tmp_68, ptr %tmp_65, ptr %tmp_67)
  call void @llvm_val_time_diff(ptr %tmp_69, ptr %wyrm_var_start_ms, ptr %wyrm_var_end_ms)
  call void @llvm_val_copy(ptr %wyrm_var_diff_result, ptr %tmp_69)
  call void @llvm_val_drop(ptr %tmp_69)
  call void @llvm_val_string(ptr %tmp_72, ptr @.str.24)
  call void @llvm_val_str(ptr %tmp_73, ptr %wyrm_var_diff_result)
  call void @llvm_val_add(ptr %tmp_71, ptr %tmp_72, ptr %tmp_73)
  call void @llvm_val_string(ptr %tmp_74, ptr @.str.25)
  call void @llvm_val_add(ptr %tmp_70, ptr %tmp_71, ptr %tmp_74)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_70)
  call void @llvm_val_eq(ptr %tmp_75, ptr %wyrm_var_diff_result, ptr %wyrm_var_delta_ms)
  call void @llvm_val_string(ptr %tmp_76, ptr @.str.26)
  call void @wyrm_fn_assert(ptr %tmp_77, ptr %tmp_75, ptr %tmp_76)
  call void @llvm_val_string(ptr %tmp_78, ptr @.str.27)
  call void @llvm_val_time_format(ptr %tmp_79, ptr %wyrm_var_unix_sec, ptr %tmp_78)
  call void @llvm_val_copy(ptr %wyrm_var_date_str, ptr %tmp_79)
  call void @llvm_val_drop(ptr %tmp_79)
  call void @llvm_val_string(ptr %tmp_81, ptr @.str.28)
  call void @llvm_val_add(ptr %tmp_80, ptr %tmp_81, ptr %wyrm_var_date_str)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_80)
  call void @llvm_val_len(ptr %tmp_83, ptr %wyrm_var_date_str)
  call void @llvm_val_number(ptr %tmp_84, double 10.0)
  call void @llvm_val_eq(ptr %tmp_82, ptr %tmp_83, ptr %tmp_84)
  call void @llvm_val_string(ptr %tmp_85, ptr @.str.29)
  call void @wyrm_fn_assert(ptr %tmp_86, ptr %tmp_82, ptr %tmp_85)
  call void @llvm_val_number(ptr %tmp_88, double 4.0)
  call void @llvm_val_char_at(ptr %tmp_89, ptr %wyrm_var_date_str, ptr %tmp_88)
  call void @llvm_val_string(ptr %tmp_90, ptr @.str.30)
  call void @llvm_val_eq(ptr %tmp_87, ptr %tmp_89, ptr %tmp_90)
  call void @llvm_val_string(ptr %tmp_91, ptr @.str.31)
  call void @wyrm_fn_assert(ptr %tmp_92, ptr %tmp_87, ptr %tmp_91)
  call void @llvm_val_number(ptr %tmp_94, double 7.0)
  call void @llvm_val_char_at(ptr %tmp_95, ptr %wyrm_var_date_str, ptr %tmp_94)
  call void @llvm_val_string(ptr %tmp_96, ptr @.str.32)
  call void @llvm_val_eq(ptr %tmp_93, ptr %tmp_95, ptr %tmp_96)
  call void @llvm_val_string(ptr %tmp_97, ptr @.str.33)
  call void @wyrm_fn_assert(ptr %tmp_98, ptr %tmp_93, ptr %tmp_97)
  call void @llvm_val_string(ptr %tmp_99, ptr @.str.34)
  call void @llvm_val_time_format_local(ptr %tmp_100, ptr %wyrm_var_unix_sec, ptr %tmp_99)
  call void @llvm_val_copy(ptr %wyrm_var_local_date_str, ptr %tmp_100)
  call void @llvm_val_drop(ptr %tmp_100)
  call void @llvm_val_string(ptr %tmp_102, ptr @.str.35)
  call void @llvm_val_add(ptr %tmp_101, ptr %tmp_102, ptr %wyrm_var_local_date_str)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_101)
  call void @llvm_val_len(ptr %tmp_104, ptr %wyrm_var_local_date_str)
  call void @llvm_val_number(ptr %tmp_105, double 19.0)
  call void @llvm_val_eq(ptr %tmp_103, ptr %tmp_104, ptr %tmp_105)
  call void @llvm_val_string(ptr %tmp_106, ptr @.str.36)
  call void @wyrm_fn_assert(ptr %tmp_107, ptr %tmp_103, ptr %tmp_106)
  call void @llvm_val_null(ptr %tmp_108)
  call void @llvm_val_time_format(ptr %tmp_109, ptr %wyrm_var_unix_sec, ptr %tmp_108)
  call void @llvm_val_copy(ptr %wyrm_var_default_fmt_str, ptr %tmp_109)
  call void @llvm_val_drop(ptr %tmp_109)
  call void @llvm_val_string(ptr %tmp_111, ptr @.str.37)
  call void @llvm_val_add(ptr %tmp_110, ptr %tmp_111, ptr %wyrm_var_default_fmt_str)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_110)
  call void @llvm_val_len(ptr %tmp_113, ptr %wyrm_var_default_fmt_str)
  call void @llvm_val_number(ptr %tmp_114, double 19.0)
  call void @llvm_val_eq(ptr %tmp_112, ptr %tmp_113, ptr %tmp_114)
  call void @llvm_val_string(ptr %tmp_115, ptr @.str.38)
  call void @wyrm_fn_assert(ptr %tmp_116, ptr %tmp_112, ptr %tmp_115)
  call void @llvm_val_string(ptr %tmp_117, ptr @.str.39)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_117)
  call void @llvm_val_null(ptr %result_ptr)
  ret void
}


define i32 @main(i32 %argc, ptr %argv) {
  call void @val_init_sys_args(i32 %argc, ptr %argv)
  %tmp_main_res = alloca %struct.Value, align 8
  call void @wyrm_fn_main(ptr %tmp_main_res)
  ret i32 0
}
