; Module generated by Wyrm 3.1.0 Self-Hosted LLVM backend
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"
%struct.Value = type { i32, %union.anon }
%union.anon = type { double }
@.str.5 = private unnamed_addr constant [15 x i8] c"Wyrm Game Test\00", align 1
@.str.6 = private unnamed_addr constant [29 x i8] c"Window created successfully!\00", align 1
@.str.7 = private unnamed_addr constant [30 x i8] c"SDL test passed successfully!\00", align 1

declare void @llvm_val_null(ptr)
declare void @llvm_val_bool(ptr, i1)
declare void @llvm_val_number(ptr, double)
declare void @llvm_val_string(ptr, ptr)
declare void @llvm_val_array_create(ptr, i32)
declare void @llvm_val_array_init(ptr, i32, ...)
declare i1 @llvm_val_to_bool(ptr)
declare void @llvm_val_print(i32, ...)
declare void @llvm_val_input(ptr, ptr)
declare void @llvm_val_len(ptr, ptr)
declare void @llvm_val_type(ptr, ptr)
declare void @llvm_val_int(ptr, ptr)
declare void @llvm_val_float(ptr, ptr)
declare void @llvm_val_str(ptr, ptr)
declare void @llvm_val_abs(ptr, ptr)
declare void @llvm_val_round(ptr, ptr)
declare void @llvm_val_pow(ptr, ptr, ptr)
declare void @llvm_val_add(ptr, ptr, ptr)
declare void @llvm_val_sub(ptr, ptr, ptr)
declare void @llvm_val_mul(ptr, ptr, ptr)
declare void @llvm_val_div(ptr, ptr, ptr)
declare void @llvm_val_mod(ptr, ptr, ptr)
declare void @llvm_val_floordiv(ptr, ptr, ptr)
declare void @llvm_val_eq(ptr, ptr, ptr)
declare void @llvm_val_ne(ptr, ptr, ptr)
declare void @llvm_val_lt(ptr, ptr, ptr)
declare void @llvm_val_gt(ptr, ptr, ptr)
declare void @llvm_val_le(ptr, ptr, ptr)
declare void @llvm_val_ge(ptr, ptr, ptr)
declare void @llvm_val_and(ptr, ptr, ptr)
declare void @llvm_val_or(ptr, ptr, ptr)
declare void @llvm_val_not(ptr, ptr)
declare void @llvm_val_array_get(ptr, ptr, ptr)
declare void @llvm_val_array_set(ptr, ptr, ptr)
declare void @llvm_val_array_append(ptr, ptr, ptr)
declare void @llvm_val_array_pop(ptr, ptr)
declare void @llvm_val_array_slice(ptr, ptr, ptr, ptr)
declare void @llvm_val_raw_malloc(ptr, ptr)
declare void @llvm_val_raw_realloc(ptr, ptr, ptr)
declare void @llvm_val_raw_free(ptr, ptr)
declare void @llvm_val_raw_ptr(ptr, ptr)
declare void @llvm_val_arena_alloc(ptr, ptr, ptr)
declare void @llvm_val_arena_reset(ptr, ptr)
declare void @llvm_val_read_file(ptr, ptr)
declare void @llvm_val_error_val(ptr, ptr)
declare void @llvm_val_write_file(ptr, ptr, ptr)
declare void @llvm_val_exit(ptr, ptr)
declare void @llvm_val_system(ptr, ptr)
declare void @llvm_val_getenv(ptr, ptr)
declare void @llvm_val_split(ptr, ptr, ptr)
declare void @llvm_val_join(ptr, ptr, ptr)
declare void @llvm_val_trim(ptr, ptr)
declare void @llvm_val_upper(ptr, ptr)
declare void @llvm_val_lower(ptr, ptr)
declare void @llvm_val_contains(ptr, ptr, ptr)
declare void @llvm_val_replace(ptr, ptr, ptr, ptr)
declare void @llvm_val_starts_with(ptr, ptr, ptr)
declare void @llvm_val_ends_with(ptr, ptr, ptr)
declare void @llvm_val_char_at(ptr, ptr, ptr)
declare void @llvm_val_ord_val(ptr, ptr)
declare void @llvm_val_chr_val(ptr, ptr)
declare void @llvm_val_to_bytes(ptr, ptr)
declare void @llvm_val_from_bytes(ptr, ptr)
declare void @llvm_val_copy(ptr, ptr)
declare ptr @val_arena_create_wrapper(ptr)
declare void @arena_destroy(ptr)
declare void @val_init_sys_args(i32, ptr)
declare void @llvm_val_struct_create(ptr, ptr, i32)
declare void @llvm_val_struct_get(ptr, ptr, ptr)
declare void @llvm_val_struct_set(ptr, ptr, ptr)
declare void @llvm_val_from_i64(ptr, i64)
declare void @llvm_val_from_u8(ptr, i8)
declare void @llvm_val_from_f32(ptr, float)
declare void @llvm_val_from_bool(ptr, i1)
declare void @llvm_val_drop(ptr)
declare void @llvm_val_json_parse(ptr, ptr)
declare void @llvm_val_json_encode(ptr, ptr)
declare void @llvm_val_json_pretty(ptr, ptr, ptr)
declare void @llvm_val_json_get(ptr, ptr, ptr)
declare void @llvm_val_json_has(ptr, ptr, ptr)
declare void @llvm_val_json_set(ptr, ptr, ptr, ptr)
declare void @llvm_val_json_object(ptr)
declare void @llvm_val_yaml_parse(ptr, ptr)
declare void @llvm_val_yaml_encode(ptr, ptr)
declare void @llvm_val_map_new(ptr)
declare void @llvm_val_map_set(ptr, ptr, ptr, ptr)
declare void @llvm_val_map_get(ptr, ptr, ptr)
declare void @llvm_val_map_has(ptr, ptr, ptr)
declare void @llvm_val_map_del(ptr, ptr, ptr)
declare void @llvm_val_map_keys(ptr, ptr)
declare void @llvm_val_map_values(ptr, ptr)
declare void @llvm_val_map_len(ptr, ptr)
declare void @llvm_val_set_new(ptr)
declare void @llvm_val_set_add(ptr, ptr, ptr)
declare void @llvm_val_set_has(ptr, ptr, ptr)
declare void @llvm_val_set_del(ptr, ptr, ptr)
declare void @llvm_val_set_union(ptr, ptr, ptr)
declare void @llvm_val_set_intersect(ptr, ptr, ptr)
declare void @llvm_val_set_to_array(ptr, ptr)
declare void @llvm_val_sdl_init(ptr)
declare void @llvm_val_sdl_quit(ptr)
declare void @llvm_val_sdl_window(ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_destroy_window(ptr, ptr)
declare void @llvm_val_sdl_poll_event(ptr)
declare void @llvm_val_sdl_clear(ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_present(ptr, ptr)
declare void @llvm_val_sdl_draw_rect(ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_draw_line(ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_delay(ptr, ptr)
declare void @llvm_val_sdl_ticks(ptr)
declare void @llvm_val_ffi_open(ptr, ptr)
declare void @llvm_val_ffi_sym(ptr, ptr, ptr)
declare void @llvm_val_ffi_call(ptr, ptr, ptr)
declare void @llvm_val_ffi_close(ptr, ptr)
@wyrm_sys_args = external global %struct.Value, align 8

define void @wyrm_fn_main(ptr %result_ptr) {
  %tmp_1 = alloca %struct.Value, align 8
  %wyrm_var_win = alloca %struct.Value, align 8
  %tmp_2 = alloca %struct.Value, align 8
  %tmp_3 = alloca %struct.Value, align 8
  %tmp_4 = alloca %struct.Value, align 8
  %tmp_5 = alloca %struct.Value, align 8
  %tmp_6 = alloca %struct.Value, align 8
  %wyrm_var_frame = alloca i32, align 4
  %wyrm_var_ev = alloca %struct.Value, align 8
  %tmp_8 = alloca %struct.Value, align 8
  %tmp_9 = alloca %struct.Value, align 8
  %tmp_10 = alloca %struct.Value, align 8
  %tmp_11 = alloca %struct.Value, align 8
  %tmp_12 = alloca %struct.Value, align 8
  %tmp_13 = alloca %struct.Value, align 8
  %tmp_14 = alloca %struct.Value, align 8
  %tmp_15 = alloca %struct.Value, align 8
  %tmp_21 = alloca %struct.Value, align 8
  %tmp_22 = alloca %struct.Value, align 8
  call void @llvm_val_sdl_init(ptr %tmp_1)
  call void @llvm_val_string(ptr %tmp_2, ptr @.str.5)
  call void @llvm_val_number(ptr %tmp_3, double 640.0)
  call void @llvm_val_number(ptr %tmp_4, double 480.0)
  call void @llvm_val_sdl_window(ptr %tmp_5, ptr %tmp_2, ptr %tmp_3, ptr %tmp_4)
  call void @llvm_val_copy(ptr %wyrm_var_win, ptr %tmp_5)
  call void @llvm_val_string(ptr %tmp_6, ptr @.str.6)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_6)
  store i32 0, ptr %wyrm_var_frame, align 4
  br label %loop_6
loop_6:
  call void @llvm_val_sdl_poll_event(ptr %tmp_8)
  call void @llvm_val_copy(ptr %wyrm_var_ev, ptr %tmp_8)
  call void @llvm_val_number(ptr %tmp_9, double 20.0)
  call void @llvm_val_number(ptr %tmp_10, double 30.0)
  call void @llvm_val_number(ptr %tmp_11, double 50.0)
  call void @llvm_val_sdl_clear(ptr %tmp_12, ptr %wyrm_var_win, ptr %tmp_9, ptr %tmp_10, ptr %tmp_11)
  call void @llvm_val_sdl_present(ptr %tmp_13, ptr %wyrm_var_win)
  call void @llvm_val_number(ptr %tmp_14, double 16.0)
  call void @llvm_val_sdl_delay(ptr %tmp_15, ptr %tmp_14)
  %val_15 = load i32, ptr %wyrm_var_frame, align 4
  %op_16 = add i32 %val_15, 1
  store i32 %op_16, ptr %wyrm_var_frame, align 4
  br label %cond_6
cond_6:
  %val_18 = load i32, ptr %wyrm_var_frame, align 4
  %cmp_i1_19 = icmp sge i32 %val_18, 10
  br i1 %cmp_i1_19, label %merge_6, label %loop_6
merge_6:
  call void @llvm_val_sdl_quit(ptr %tmp_21)
  call void @llvm_val_string(ptr %tmp_22, ptr @.str.7)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_22)
  call void @llvm_val_null(ptr %result_ptr)
  ret void
}


define i32 @main(i32 %argc, ptr %argv) {
  call void @val_init_sys_args(i32 %argc, ptr %argv)
  %tmp_main_res = alloca %struct.Value, align 8
  call void @wyrm_fn_main(ptr %tmp_main_res)
  ret i32 0
}
