; Module generated by Wyrm 3.1.0 Self-Hosted LLVM backend
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"
%struct.Value = type { i32, %union.anon }
%union.anon = type { double }
@.str.5 = private unnamed_addr constant [9 x i8] c"i64 sum:\00", align 1
@.str.6 = private unnamed_addr constant [10 x i8] c"u8 total:\00", align 1
@.str.7 = private unnamed_addr constant [23 x i8] c"i64 loop sum (0..100):\00", align 1
@.str.8 = private unnamed_addr constant [9 x i8] c"f32 add:\00", align 1
@.str.9 = private unnamed_addr constant [24 x i8] c"f64 circle area (r=10):\00", align 1
@.str.10 = private unnamed_addr constant [10 x i8] c"bool and:\00", align 1
@.str.11 = private unnamed_addr constant [9 x i8] c"bool or:\00", align 1
@.str.12 = private unnamed_addr constant [52 x i8] c"=== Wyrm v3.1.0 Comprehensive Static Types Test ===\00", align 1
@.str.13 = private unnamed_addr constant [45 x i8] c"=== All Static Types Passed Successfully ===\00", align 1

declare void @llvm_val_null(ptr)
declare void @llvm_val_bool(ptr, i1)
declare void @llvm_val_number(ptr, double)
declare void @llvm_val_string(ptr, ptr)
declare void @llvm_val_array_create(ptr, i32)
declare void @llvm_val_array_init(ptr, i32, ...)
declare i1 @llvm_val_to_bool(ptr)
declare void @llvm_val_print(i32, ...)
declare void @llvm_val_input(ptr, ptr)
declare void @llvm_val_len(ptr, ptr)
declare void @llvm_val_type(ptr, ptr)
declare void @llvm_val_int(ptr, ptr)
declare void @llvm_val_float(ptr, ptr)
declare void @llvm_val_str(ptr, ptr)
declare void @llvm_val_abs(ptr, ptr)
declare void @llvm_val_round(ptr, ptr)
declare void @llvm_val_pow(ptr, ptr, ptr)
declare void @llvm_val_add(ptr, ptr, ptr)
declare void @llvm_val_sub(ptr, ptr, ptr)
declare void @llvm_val_mul(ptr, ptr, ptr)
declare void @llvm_val_div(ptr, ptr, ptr)
declare void @llvm_val_mod(ptr, ptr, ptr)
declare void @llvm_val_floordiv(ptr, ptr, ptr)
declare void @llvm_val_eq(ptr, ptr, ptr)
declare void @llvm_val_ne(ptr, ptr, ptr)
declare void @llvm_val_lt(ptr, ptr, ptr)
declare void @llvm_val_gt(ptr, ptr, ptr)
declare void @llvm_val_le(ptr, ptr, ptr)
declare void @llvm_val_ge(ptr, ptr, ptr)
declare void @llvm_val_and(ptr, ptr, ptr)
declare void @llvm_val_or(ptr, ptr, ptr)
declare void @llvm_val_not(ptr, ptr)
declare void @llvm_val_array_get(ptr, ptr, ptr)
declare void @llvm_val_array_set(ptr, ptr, ptr)
declare void @llvm_val_array_append(ptr, ptr, ptr)
declare void @llvm_val_array_pop(ptr, ptr)
declare void @llvm_val_array_slice(ptr, ptr, ptr, ptr)
declare void @llvm_val_raw_malloc(ptr, ptr)
declare void @llvm_val_raw_realloc(ptr, ptr, ptr)
declare void @llvm_val_raw_free(ptr, ptr)
declare void @llvm_val_raw_ptr(ptr, ptr)
declare void @llvm_val_arena_alloc(ptr, ptr, ptr)
declare void @llvm_val_arena_reset(ptr, ptr)
declare void @llvm_val_read_file(ptr, ptr)
declare void @llvm_val_error_val(ptr, ptr)
declare void @llvm_val_write_file(ptr, ptr, ptr)
declare void @llvm_val_exit(ptr, ptr)
declare void @llvm_val_system(ptr, ptr)
declare void @llvm_val_getenv(ptr, ptr)
declare void @llvm_val_split(ptr, ptr, ptr)
declare void @llvm_val_join(ptr, ptr, ptr)
declare void @llvm_val_trim(ptr, ptr)
declare void @llvm_val_upper(ptr, ptr)
declare void @llvm_val_lower(ptr, ptr)
declare void @llvm_val_contains(ptr, ptr, ptr)
declare void @llvm_val_replace(ptr, ptr, ptr, ptr)
declare void @llvm_val_starts_with(ptr, ptr, ptr)
declare void @llvm_val_ends_with(ptr, ptr, ptr)
declare void @llvm_val_char_at(ptr, ptr, ptr)
declare void @llvm_val_ord_val(ptr, ptr)
declare void @llvm_val_chr_val(ptr, ptr)
declare void @llvm_val_to_bytes(ptr, ptr)
declare void @llvm_val_from_bytes(ptr, ptr)
declare void @llvm_val_copy(ptr, ptr)
declare ptr @val_arena_create_wrapper(ptr)
declare void @arena_destroy(ptr)
declare void @val_init_sys_args(i32, ptr)
declare void @llvm_val_struct_create(ptr, ptr, i32)
declare void @llvm_val_struct_get(ptr, ptr, ptr)
declare void @llvm_val_struct_set(ptr, ptr, ptr)
declare void @llvm_val_from_i64(ptr, i64)
declare void @llvm_val_from_u8(ptr, i8)
declare void @llvm_val_from_f32(ptr, float)
declare void @llvm_val_from_bool(ptr, i1)
declare void @llvm_val_drop(ptr)
declare void @llvm_val_json_parse(ptr, ptr)
declare void @llvm_val_json_encode(ptr, ptr)
declare void @llvm_val_json_pretty(ptr, ptr, ptr)
declare void @llvm_val_json_get(ptr, ptr, ptr)
declare void @llvm_val_json_has(ptr, ptr, ptr)
declare void @llvm_val_json_set(ptr, ptr, ptr, ptr)
declare void @llvm_val_json_object(ptr)
declare void @llvm_val_yaml_parse(ptr, ptr)
declare void @llvm_val_yaml_encode(ptr, ptr)
declare void @llvm_val_map_new(ptr)
declare void @llvm_val_map_set(ptr, ptr, ptr, ptr)
declare void @llvm_val_map_get(ptr, ptr, ptr)
declare void @llvm_val_map_has(ptr, ptr, ptr)
declare void @llvm_val_map_del(ptr, ptr, ptr)
declare void @llvm_val_map_keys(ptr, ptr)
declare void @llvm_val_map_values(ptr, ptr)
declare void @llvm_val_map_len(ptr, ptr)
declare void @llvm_val_set_new(ptr)
declare void @llvm_val_set_add(ptr, ptr, ptr)
declare void @llvm_val_set_has(ptr, ptr, ptr)
declare void @llvm_val_set_del(ptr, ptr, ptr)
declare void @llvm_val_set_union(ptr, ptr, ptr)
declare void @llvm_val_set_intersect(ptr, ptr, ptr)
declare void @llvm_val_set_to_array(ptr, ptr)
declare void @llvm_val_sdl_init(ptr)
declare void @llvm_val_sdl_quit(ptr)
declare void @llvm_val_sdl_window(ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_destroy_window(ptr, ptr)
declare void @llvm_val_sdl_poll_event(ptr)
declare void @llvm_val_sdl_clear(ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_present(ptr, ptr)
declare void @llvm_val_sdl_draw_rect(ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_draw_line(ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr)
declare void @llvm_val_sdl_delay(ptr, ptr)
declare void @llvm_val_sdl_ticks(ptr)
declare void @llvm_val_ffi_open(ptr, ptr)
declare void @llvm_val_ffi_sym(ptr, ptr, ptr)
declare void @llvm_val_ffi_call(ptr, ptr, ptr)
declare void @llvm_val_ffi_close(ptr, ptr)
@wyrm_sys_args = external global %struct.Value, align 8

define void @wyrm_fn_test_integers(ptr %result_ptr) {
  %wyrm_var_a = alloca i64, align 8
  %wyrm_var_b = alloca i64, align 8
  %wyrm_var_sum_i64 = alloca i64, align 8
  %tmp_4 = alloca %struct.Value, align 8
  %tmp_5 = alloca %struct.Value, align 8
  %wyrm_var_u = alloca i8, align 1
  %wyrm_var_add_val = alloca i8, align 1
  %wyrm_var_total_u8 = alloca i8, align 1
  %tmp_10 = alloca %struct.Value, align 8
  %tmp_11 = alloca %struct.Value, align 8
  %wyrm_var_count = alloca i64, align 8
  %wyrm_var_total = alloca i64, align 8
  %tmp_22 = alloca %struct.Value, align 8
  %tmp_23 = alloca %struct.Value, align 8
  store i64 5000000000, ptr %wyrm_var_a, align 8
  store i64 4000000000, ptr %wyrm_var_b, align 8
  %val_0 = load i64, ptr %wyrm_var_a, align 8
  %val_1 = load i64, ptr %wyrm_var_b, align 8
  %op_2 = add i64 %val_0, %val_1
  store i64 %op_2, ptr %wyrm_var_sum_i64, align 8
  call void @llvm_val_string(ptr %tmp_4, ptr @.str.5)
  %raw_val_5 = load i64, ptr %wyrm_var_sum_i64, align 8
  call void @llvm_val_from_i64(ptr %tmp_5, i64 %raw_val_5)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_4, ptr %tmp_5)
  store i8 200, ptr %wyrm_var_u, align 1
  store i8 55, ptr %wyrm_var_add_val, align 1
  %val_6 = load i8, ptr %wyrm_var_u, align 1
  %val_7 = load i8, ptr %wyrm_var_add_val, align 1
  %op_8 = add i8 %val_6, %val_7
  store i8 %op_8, ptr %wyrm_var_total_u8, align 1
  call void @llvm_val_string(ptr %tmp_10, ptr @.str.6)
  %raw_val_11 = load i8, ptr %wyrm_var_total_u8, align 1
  call void @llvm_val_from_u8(ptr %tmp_11, i8 %raw_val_11)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_10, ptr %tmp_11)
  store i64 0, ptr %wyrm_var_count, align 8
  store i64 0, ptr %wyrm_var_total, align 8
  br label %loop_12
loop_12:
  %val_13 = load i64, ptr %wyrm_var_total, align 8
  %val_14 = load i64, ptr %wyrm_var_count, align 8
  %op_15 = add i64 %val_13, %val_14
  store i64 %op_15, ptr %wyrm_var_total, align 8
  %val_16 = load i64, ptr %wyrm_var_count, align 8
  %op_17 = add i64 %val_16, 1
  store i64 %op_17, ptr %wyrm_var_count, align 8
  br label %cond_12
cond_12:
  %val_19 = load i64, ptr %wyrm_var_count, align 8
  %cmp_i1_20 = icmp sgt i64 %val_19, 100
  br i1 %cmp_i1_20, label %merge_12, label %loop_12
merge_12:
  call void @llvm_val_string(ptr %tmp_22, ptr @.str.7)
  %raw_val_23 = load i64, ptr %wyrm_var_total, align 8
  call void @llvm_val_from_i64(ptr %tmp_23, i64 %raw_val_23)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_22, ptr %tmp_23)
  call void @llvm_val_null(ptr %result_ptr)
  ret void
}

define void @wyrm_fn_test_floats(ptr %result_ptr) {
  %wyrm_var_x = alloca float, align 4
  %wyrm_var_y = alloca float, align 4
  %wyrm_var_res_f32 = alloca float, align 4
  %tmp_4 = alloca %struct.Value, align 8
  %tmp_5 = alloca %struct.Value, align 8
  %wyrm_var_pi = alloca double, align 8
  %wyrm_var_radius = alloca double, align 8
  %wyrm_var_area = alloca double, align 8
  %tmp_12 = alloca %struct.Value, align 8
  %tmp_13 = alloca %struct.Value, align 8
  store float 1.25, ptr %wyrm_var_x, align 4
  store float 2.75, ptr %wyrm_var_y, align 4
  %val_0 = load float, ptr %wyrm_var_x, align 4
  %val_1 = load float, ptr %wyrm_var_y, align 4
  %op_2 = fadd float %val_0, %val_1
  store float %op_2, ptr %wyrm_var_res_f32, align 4
  call void @llvm_val_string(ptr %tmp_4, ptr @.str.8)
  %raw_val_5 = load float, ptr %wyrm_var_res_f32, align 4
  call void @llvm_val_from_f32(ptr %tmp_5, float %raw_val_5)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_4, ptr %tmp_5)
  store double 3.141592653589793, ptr %wyrm_var_pi, align 8
  store double 10.0, ptr %wyrm_var_radius, align 8
  %val_6 = load double, ptr %wyrm_var_pi, align 8
  %val_7 = load double, ptr %wyrm_var_radius, align 8
  %op_8 = fmul double %val_6, %val_7
  %val_9 = load double, ptr %wyrm_var_radius, align 8
  %op_10 = fmul double %op_8, %val_9
  store double %op_10, ptr %wyrm_var_area, align 8
  call void @llvm_val_string(ptr %tmp_12, ptr @.str.9)
  %raw_val_13 = load double, ptr %wyrm_var_area, align 8
  call void @llvm_val_number(ptr %tmp_13, double %raw_val_13)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_12, ptr %tmp_13)
  call void @llvm_val_null(ptr %result_ptr)
  ret void
}

define void @wyrm_fn_test_booleans(ptr %result_ptr) {
  %wyrm_var_flag1 = alloca i1, align 1
  %wyrm_var_flag2 = alloca i1, align 1
  %wyrm_var_result_and = alloca i1, align 1
  %wyrm_var_result_or = alloca i1, align 1
  %tmp_7 = alloca %struct.Value, align 8
  %tmp_8 = alloca %struct.Value, align 8
  %tmp_10 = alloca %struct.Value, align 8
  %tmp_11 = alloca %struct.Value, align 8
  store i1 1, ptr %wyrm_var_flag1, align 1
  store i1 0, ptr %wyrm_var_flag2, align 1
  %val_0 = load i1, ptr %wyrm_var_flag1, align 1
  %val_1 = load i1, ptr %wyrm_var_flag2, align 1
  %op_2 = and i1 %val_0, %val_1
  store i1 %op_2, ptr %wyrm_var_result_and, align 1
  %val_3 = load i1, ptr %wyrm_var_flag1, align 1
  %val_4 = load i1, ptr %wyrm_var_flag2, align 1
  %op_5 = or i1 %val_3, %val_4
  store i1 %op_5, ptr %wyrm_var_result_or, align 1
  call void @llvm_val_string(ptr %tmp_7, ptr @.str.10)
  %raw_val_8 = load i1, ptr %wyrm_var_result_and, align 1
  call void @llvm_val_from_bool(ptr %tmp_8, i1 %raw_val_8)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_7, ptr %tmp_8)
  call void @llvm_val_string(ptr %tmp_10, ptr @.str.11)
  %raw_val_11 = load i1, ptr %wyrm_var_result_or, align 1
  call void @llvm_val_from_bool(ptr %tmp_11, i1 %raw_val_11)
  call void (i32, ...) @llvm_val_print(i32 2, ptr %tmp_10, ptr %tmp_11)
  call void @llvm_val_null(ptr %result_ptr)
  ret void
}

define void @wyrm_fn_main(ptr %result_ptr) {
  %tmp_1 = alloca %struct.Value, align 8
  %tmp_2 = alloca %struct.Value, align 8
  %tmp_3 = alloca %struct.Value, align 8
  %tmp_4 = alloca %struct.Value, align 8
  %tmp_5 = alloca %struct.Value, align 8
  call void @llvm_val_string(ptr %tmp_1, ptr @.str.12)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_1)
  call void @wyrm_fn_test_integers(ptr %tmp_2)
  call void @wyrm_fn_test_floats(ptr %tmp_3)
  call void @wyrm_fn_test_booleans(ptr %tmp_4)
  call void @llvm_val_string(ptr %tmp_5, ptr @.str.13)
  call void (i32, ...) @llvm_val_print(i32 1, ptr %tmp_5)
  call void @llvm_val_null(ptr %result_ptr)
  ret void
}


define i32 @main(i32 %argc, ptr %argv) {
  call void @val_init_sys_args(i32 %argc, ptr %argv)
  %tmp_main_res = alloca %struct.Value, align 8
  call void @wyrm_fn_main(ptr %tmp_main_res)
  ret i32 0
}
